#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run Isaac simulation on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
ISAAC_VENV="${ISAAC_VENV:-/public/home/yanhongru/envs/isaac_arena_py312}"
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
LOG_DIR="${LOG_DIR:-${ROOT_DIR}/logs/core_world_prismatic_carrier_stand}"
OUTPUT_DIR="${OUTPUT_DIR:-${ROOT_DIR}/experiments/outputs/core_world_prismatic_carrier_stand/${STAMP}}"
STEPS="${STEPS:-360}"
PAYLOAD_MODE="${PAYLOAD_MODE:-fixed_joint_to_torso}"
PAYLOAD_MASS="${PAYLOAD_MASS:-6.0}"
PAYLOAD_SIZE_X="${PAYLOAD_SIZE_X:-0.34}"
PAYLOAD_SIZE_Y="${PAYLOAD_SIZE_Y:-0.24}"
PAYLOAD_SIZE_Z="${PAYLOAD_SIZE_Z:-0.24}"
TORSO_MASS="${TORSO_MASS:-32.0}"
TORSO_Z="${TORSO_Z:-0.62}"
PAYLOAD_LOCAL_X="${PAYLOAD_LOCAL_X:-0.24}"
PAYLOAD_LOCAL_Z="${PAYLOAD_LOCAL_Z:-0.04}"
TRAY_LOCAL_X="${TRAY_LOCAL_X:-0.08}"
TRAY_LOCAL_Z="${TRAY_LOCAL_Z:-0.12}"
TRAY_SIZE_X="${TRAY_SIZE_X:-0.58}"
TRAY_SIZE_Y="${TRAY_SIZE_Y:-0.42}"
TRAY_SIZE_Z="${TRAY_SIZE_Z:-0.035}"
TRAY_RAIL_HEIGHT="${TRAY_RAIL_HEIGHT:-0.11}"
TRAY_RAIL_THICKNESS="${TRAY_RAIL_THICKNESS:-0.035}"
TRAY_MASS="${TRAY_MASS:-4.0}"
ENABLE_TRAY_LID="${ENABLE_TRAY_LID:-0}"
TRAY_LID_CLEARANCE="${TRAY_LID_CLEARANCE:-0.025}"
TRAY_LID_THICKNESS="${TRAY_LID_THICKNESS:-0.035}"
TRAY_LID_MASS="${TRAY_LID_MASS:-2.0}"
CRADLE_CLEARANCE_X="${CRADLE_CLEARANCE_X:-0.025}"
CRADLE_CLEARANCE_Y="${CRADLE_CLEARANCE_Y:-0.040}"
CRADLE_WALL_HEIGHT="${CRADLE_WALL_HEIGHT:-0.26}"
CRADLE_WALL_THICKNESS="${CRADLE_WALL_THICKNESS:-0.030}"
CRADLE_PART_MASS="${CRADLE_PART_MASS:-1.0}"
MOTION_MODE="${MOTION_MODE:-stand}"
ENABLE_HORIZONTAL_LEGS="${ENABLE_HORIZONTAL_LEGS:-0}"
TARGET_X="${TARGET_X:-0.20}"
GAIT_DRIVE_TARGET_X="${GAIT_DRIVE_TARGET_X:-}"
STEP_LENGTH="${STEP_LENGTH:-0.08}"
STEP_HEIGHT="${STEP_HEIGHT:-0.09}"
GAIT_PERIOD_STEPS="${GAIT_PERIOD_STEPS:-160}"
SWING_FRACTION="${SWING_FRACTION:-0.22}"
SYNC_CYCLE_PAUSE_FRACTION="${SYNC_CYCLE_PAUSE_FRACTION:-0.0}"
FEEDBACK_TILT_HOLD_THRESHOLD="${FEEDBACK_TILT_HOLD_THRESHOLD:-0.22}"
FEEDBACK_PAYLOAD_ERROR_HOLD_THRESHOLD="${FEEDBACK_PAYLOAD_ERROR_HOLD_THRESHOLD:-0.12}"
GATED_STEP_MAX_TRAVEL_LOSS="${GATED_STEP_MAX_TRAVEL_LOSS:-0.015}"
GATED_STEP_RECOVERY_PHASE="${GATED_STEP_RECOVERY_PHASE:-0.43}"
GATED_STEP_LOSS_REBASELINE_STEPS="${GATED_STEP_LOSS_REBASELINE_STEPS:-0}"
PRELIFT_RESET_LIFT_FRACTION="${PRELIFT_RESET_LIFT_FRACTION:-0.30}"
PRELIFT_RESET_LOWER_FRACTION="${PRELIFT_RESET_LOWER_FRACTION:-0.30}"
PRELIFT_STANCE_OVERDRIVE="${PRELIFT_STANCE_OVERDRIVE:-1.0}"
GUARDED_STEP_TARGET_TOLERANCE="${GUARDED_STEP_TARGET_TOLERANCE:-0.018}"
GUARDED_STOP_TARGET_X="${GUARDED_STOP_TARGET_X:-}"
ENABLE_ACTIVE_PROBE="${ENABLE_ACTIVE_PROBE:-0}"
ACTIVE_PROBE_STEPS="${ACTIVE_PROBE_STEPS:-0}"
ACTIVE_PROBE_LIFT_AMPLITUDE="${ACTIVE_PROBE_LIFT_AMPLITUDE:-0.030}"
ACTIVE_PROBE_HORIZONTAL_AMPLITUDE="${ACTIVE_PROBE_HORIZONTAL_AMPLITUDE:-0.0}"
ENABLE_PROBE_ADAPTIVE_GAIT="${ENABLE_PROBE_ADAPTIVE_GAIT:-0}"
PROBE_ADAPTIVE_MEDIUM_RISK_THRESHOLD="${PROBE_ADAPTIVE_MEDIUM_RISK_THRESHOLD:-0.25}"
PROBE_ADAPTIVE_HIGH_RISK_THRESHOLD="${PROBE_ADAPTIVE_HIGH_RISK_THRESHOLD:-0.75}"
PROBE_ADAPTIVE_MEDIUM_GAIT_DRIVE_SCALE="${PROBE_ADAPTIVE_MEDIUM_GAIT_DRIVE_SCALE:-0.95}"
PROBE_ADAPTIVE_HIGH_GAIT_DRIVE_SCALE="${PROBE_ADAPTIVE_HIGH_GAIT_DRIVE_SCALE:-0.85}"
ENABLE_PROBE_ADAPTIVE_POSTURE="${ENABLE_PROBE_ADAPTIVE_POSTURE:-0}"
PROBE_ADAPTIVE_MEDIUM_POSTURE_LEG_TARGET_OFFSET="${PROBE_ADAPTIVE_MEDIUM_POSTURE_LEG_TARGET_OFFSET:-0.012}"
PROBE_ADAPTIVE_HIGH_POSTURE_LEG_TARGET_OFFSET="${PROBE_ADAPTIVE_HIGH_POSTURE_LEG_TARGET_OFFSET:-0.024}"
QUASISTATIC_COMPENSATE_SETTLE_DRIFT="${QUASISTATIC_COMPENSATE_SETTLE_DRIFT:-0}"
SETTLE_STEPS="${SETTLE_STEPS:-0}"
RAMP_STEPS="${RAMP_STEPS:-1}"
STANCE_HALF_LENGTH="${STANCE_HALF_LENGTH:-0.30}"
STANCE_HALF_WIDTH="${STANCE_HALF_WIDTH:-0.24}"
FOOT_LENGTH="${FOOT_LENGTH:-0.34}"
FOOT_WIDTH="${FOOT_WIDTH:-0.18}"
FOOT_HEIGHT="${FOOT_HEIGHT:-0.055}"
FOOT_MASS="${FOOT_MASS:-2.8}"
FOOT_CONTACT_Z_THRESHOLD="${FOOT_CONTACT_Z_THRESHOLD:-0.050}"
ENABLE_STANCE_FOOT_LATCH="${ENABLE_STANCE_FOOT_LATCH:-0}"
STANCE_FOOT_LATCH_LIFT_THRESHOLD="${STANCE_FOOT_LATCH_LIFT_THRESHOLD:-0.010}"
LEG_TARGET="${LEG_TARGET:--0.50}"
LEG_LOWER="${LEG_LOWER:--0.75}"
LEG_UPPER="${LEG_UPPER:--0.25}"
LEG_STIFFNESS="${LEG_STIFFNESS:-18000.0}"
LEG_DAMPING="${LEG_DAMPING:-1800.0}"
LEG_MAX_FORCE="${LEG_MAX_FORCE:-25000.0}"
ENABLE_BALANCE_LEG_SERVO="${ENABLE_BALANCE_LEG_SERVO:-0}"
BALANCE_ROLL_GAIN="${BALANCE_ROLL_GAIN:-0.0}"
BALANCE_PITCH_GAIN="${BALANCE_PITCH_GAIN:-0.0}"
BALANCE_MAX_CORRECTION="${BALANCE_MAX_CORRECTION:-0.05}"
X_SLIDE_LIMIT="${X_SLIDE_LIMIT:-0.14}"
X_SLIDE_STIFFNESS="${X_SLIDE_STIFFNESS:-9000.0}"
X_SLIDE_DAMPING="${X_SLIDE_DAMPING:-900.0}"
X_SLIDE_MAX_FORCE="${X_SLIDE_MAX_FORCE:-12000.0}"
SWING_X_FORCE_SCALE="${SWING_X_FORCE_SCALE:-1.0}"
STATIC_FRICTION="${STATIC_FRICTION:-3.0}"
DYNAMIC_FRICTION="${DYNAMIC_FRICTION:-2.5}"
FALL_Z="${FALL_Z:-0.42}"
DROP_Z="${DROP_Z:-0.24}"
MAX_STAND_DRIFT="${MAX_STAND_DRIFT:-0.08}"
DEVICE="${DEVICE:-cpu}"
RENDER="${RENDER:-0}"
EXPERIENCE="${EXPERIENCE:-${ROOT_DIR}/external/IsaacLab-Arena/submodules/IsaacLab/apps/isaaclab.python.headless.kit}"
OV_REGISTRY_MIRROR="${OV_REGISTRY_MIRROR:-/public/home/yanhongru/ov_registry_mirror}"
KIT_ARGS="${KIT_ARGS:---/exts/omni.kit.registry.nucleus/registries/0/url=${OV_REGISTRY_MIRROR}/kit_prod_default --/exts/omni.kit.registry.nucleus/registries/1/url=${OV_REGISTRY_MIRROR}/kit_prod_sdk}"

mkdir -p "${LOG_DIR}" "${OUTPUT_DIR}"
if [[ ! -x "${ISAAC_VENV}/bin/python" ]]; then
  echo "Isaac/Arena Python not found: ${ISAAC_VENV}/bin/python" >&2
  exit 3
fi

EXTRA_ARGS=()
if [[ "${RENDER}" == "1" ]]; then
  EXTRA_ARGS+=(--render --enable_cameras)
fi
if [[ "${ENABLE_HORIZONTAL_LEGS}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-horizontal-legs)
fi
if [[ "${ENABLE_TRAY_LID}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-tray-lid)
fi
if [[ "${ENABLE_BALANCE_LEG_SERVO}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-balance-leg-servo)
fi
if [[ "${ENABLE_STANCE_FOOT_LATCH}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-stance-foot-latch)
fi
if [[ "${QUASISTATIC_COMPENSATE_SETTLE_DRIFT}" == "1" ]]; then
  EXTRA_ARGS+=(--quasistatic-compensate-settle-drift)
fi
if [[ -n "${GAIT_DRIVE_TARGET_X}" ]]; then
  EXTRA_ARGS+=(--gait-drive-target-x "${GAIT_DRIVE_TARGET_X}")
fi
if [[ -n "${GUARDED_STOP_TARGET_X}" ]]; then
  EXTRA_ARGS+=(--guarded-stop-target-x "${GUARDED_STOP_TARGET_X}")
fi
if [[ "${ENABLE_ACTIVE_PROBE}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-active-probe)
fi
if [[ "${ENABLE_PROBE_ADAPTIVE_GAIT}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-probe-adaptive-gait)
fi
if [[ "${ENABLE_PROBE_ADAPTIVE_POSTURE}" == "1" ]]; then
  EXTRA_ARGS+=(--enable-probe-adaptive-posture)
fi

LOG_PATH="${LOG_DIR}/core_world_prismatic_carrier_stand_${STAMP}.log"
cd "${ROOT_DIR}"
echo "[CONFIG] STAMP=${STAMP} PAYLOAD_MODE=${PAYLOAD_MODE} PAYLOAD_MASS=${PAYLOAD_MASS} PAYLOAD_SIZE=${PAYLOAD_SIZE_X},${PAYLOAD_SIZE_Y},${PAYLOAD_SIZE_Z} MOTION_MODE=${MOTION_MODE} ENABLE_HORIZONTAL_LEGS=${ENABLE_HORIZONTAL_LEGS} ENABLE_TRAY_LID=${ENABLE_TRAY_LID} ENABLE_BALANCE_LEG_SERVO=${ENABLE_BALANCE_LEG_SERVO} ENABLE_STANCE_FOOT_LATCH=${ENABLE_STANCE_FOOT_LATCH} QUASISTATIC_COMPENSATE_SETTLE_DRIFT=${QUASISTATIC_COMPENSATE_SETTLE_DRIFT} ENABLE_ACTIVE_PROBE=${ENABLE_ACTIVE_PROBE} ACTIVE_PROBE_STEPS=${ACTIVE_PROBE_STEPS} ACTIVE_PROBE_LIFT_AMPLITUDE=${ACTIVE_PROBE_LIFT_AMPLITUDE} ACTIVE_PROBE_HORIZONTAL_AMPLITUDE=${ACTIVE_PROBE_HORIZONTAL_AMPLITUDE} ENABLE_PROBE_ADAPTIVE_GAIT=${ENABLE_PROBE_ADAPTIVE_GAIT} PROBE_ADAPTIVE_MEDIUM_RISK_THRESHOLD=${PROBE_ADAPTIVE_MEDIUM_RISK_THRESHOLD} PROBE_ADAPTIVE_HIGH_RISK_THRESHOLD=${PROBE_ADAPTIVE_HIGH_RISK_THRESHOLD} PROBE_ADAPTIVE_MEDIUM_GAIT_DRIVE_SCALE=${PROBE_ADAPTIVE_MEDIUM_GAIT_DRIVE_SCALE} PROBE_ADAPTIVE_HIGH_GAIT_DRIVE_SCALE=${PROBE_ADAPTIVE_HIGH_GAIT_DRIVE_SCALE} ENABLE_PROBE_ADAPTIVE_POSTURE=${ENABLE_PROBE_ADAPTIVE_POSTURE} PROBE_ADAPTIVE_MEDIUM_POSTURE_LEG_TARGET_OFFSET=${PROBE_ADAPTIVE_MEDIUM_POSTURE_LEG_TARGET_OFFSET} PROBE_ADAPTIVE_HIGH_POSTURE_LEG_TARGET_OFFSET=${PROBE_ADAPTIVE_HIGH_POSTURE_LEG_TARGET_OFFSET} STEPS=${STEPS} TARGET_X=${TARGET_X} GAIT_DRIVE_TARGET_X=${GAIT_DRIVE_TARGET_X:-none} GUARDED_STOP_TARGET_X=${GUARDED_STOP_TARGET_X:-none} SETTLE_STEPS=${SETTLE_STEPS} RAMP_STEPS=${RAMP_STEPS} GAIT_PERIOD_STEPS=${GAIT_PERIOD_STEPS} SYNC_CYCLE_PAUSE_FRACTION=${SYNC_CYCLE_PAUSE_FRACTION} FEEDBACK_TILT_HOLD_THRESHOLD=${FEEDBACK_TILT_HOLD_THRESHOLD} FEEDBACK_PAYLOAD_ERROR_HOLD_THRESHOLD=${FEEDBACK_PAYLOAD_ERROR_HOLD_THRESHOLD} GATED_STEP_MAX_TRAVEL_LOSS=${GATED_STEP_MAX_TRAVEL_LOSS} GATED_STEP_RECOVERY_PHASE=${GATED_STEP_RECOVERY_PHASE} GATED_STEP_LOSS_REBASELINE_STEPS=${GATED_STEP_LOSS_REBASELINE_STEPS} PRELIFT_RESET_LIFT_FRACTION=${PRELIFT_RESET_LIFT_FRACTION} PRELIFT_RESET_LOWER_FRACTION=${PRELIFT_RESET_LOWER_FRACTION} PRELIFT_STANCE_OVERDRIVE=${PRELIFT_STANCE_OVERDRIVE} SWING_X_FORCE_SCALE=${SWING_X_FORCE_SCALE} GUARDED_STEP_TARGET_TOLERANCE=${GUARDED_STEP_TARGET_TOLERANCE} TRAY_SIZE=${TRAY_SIZE_X},${TRAY_SIZE_Y},${TRAY_SIZE_Z} TRAY_LOCAL=${TRAY_LOCAL_X},${TRAY_LOCAL_Z}"
"${ISAAC_VENV}/bin/python" \
  "${ROOT_DIR}/scripts/isaac/build_core_world_prismatic_carrier_stand.py" \
  --viz none \
  --experience "${EXPERIENCE}" \
  --device "${DEVICE}" \
  --kit_args "${KIT_ARGS}" \
  --steps "${STEPS}" \
  --payload-mode "${PAYLOAD_MODE}" \
  --payload-mass "${PAYLOAD_MASS}" \
  --payload-size "${PAYLOAD_SIZE_X}" "${PAYLOAD_SIZE_Y}" "${PAYLOAD_SIZE_Z}" \
  --torso-mass "${TORSO_MASS}" \
  --torso-z "${TORSO_Z}" \
  --payload-local-x "${PAYLOAD_LOCAL_X}" \
  --payload-local-z "${PAYLOAD_LOCAL_Z}" \
  --tray-local-x "${TRAY_LOCAL_X}" \
  --tray-local-z "${TRAY_LOCAL_Z}" \
  --tray-size "${TRAY_SIZE_X}" "${TRAY_SIZE_Y}" "${TRAY_SIZE_Z}" \
  --tray-rail-height "${TRAY_RAIL_HEIGHT}" \
  --tray-rail-thickness "${TRAY_RAIL_THICKNESS}" \
  --tray-mass "${TRAY_MASS}" \
  --tray-lid-clearance "${TRAY_LID_CLEARANCE}" \
  --tray-lid-thickness "${TRAY_LID_THICKNESS}" \
  --tray-lid-mass "${TRAY_LID_MASS}" \
  --cradle-clearance-x "${CRADLE_CLEARANCE_X}" \
  --cradle-clearance-y "${CRADLE_CLEARANCE_Y}" \
  --cradle-wall-height "${CRADLE_WALL_HEIGHT}" \
  --cradle-wall-thickness "${CRADLE_WALL_THICKNESS}" \
  --cradle-part-mass "${CRADLE_PART_MASS}" \
  --motion-mode "${MOTION_MODE}" \
  --target-x "${TARGET_X}" \
  --step-length "${STEP_LENGTH}" \
  --step-height "${STEP_HEIGHT}" \
  --gait-period-steps "${GAIT_PERIOD_STEPS}" \
  --swing-fraction "${SWING_FRACTION}" \
  --sync-cycle-pause-fraction "${SYNC_CYCLE_PAUSE_FRACTION}" \
  --feedback-tilt-hold-threshold "${FEEDBACK_TILT_HOLD_THRESHOLD}" \
  --feedback-payload-error-hold-threshold "${FEEDBACK_PAYLOAD_ERROR_HOLD_THRESHOLD}" \
  --gated-step-max-travel-loss "${GATED_STEP_MAX_TRAVEL_LOSS}" \
  --gated-step-recovery-phase "${GATED_STEP_RECOVERY_PHASE}" \
  --gated-step-loss-rebaseline-steps "${GATED_STEP_LOSS_REBASELINE_STEPS}" \
  --prelift-reset-lift-fraction "${PRELIFT_RESET_LIFT_FRACTION}" \
  --prelift-reset-lower-fraction "${PRELIFT_RESET_LOWER_FRACTION}" \
  --prelift-stance-overdrive "${PRELIFT_STANCE_OVERDRIVE}" \
  --guarded-step-target-tolerance "${GUARDED_STEP_TARGET_TOLERANCE}" \
  --active-probe-steps "${ACTIVE_PROBE_STEPS}" \
  --active-probe-lift-amplitude "${ACTIVE_PROBE_LIFT_AMPLITUDE}" \
  --active-probe-horizontal-amplitude "${ACTIVE_PROBE_HORIZONTAL_AMPLITUDE}" \
  --probe-adaptive-medium-risk-threshold "${PROBE_ADAPTIVE_MEDIUM_RISK_THRESHOLD}" \
  --probe-adaptive-high-risk-threshold "${PROBE_ADAPTIVE_HIGH_RISK_THRESHOLD}" \
  --probe-adaptive-medium-gait-drive-scale "${PROBE_ADAPTIVE_MEDIUM_GAIT_DRIVE_SCALE}" \
  --probe-adaptive-high-gait-drive-scale "${PROBE_ADAPTIVE_HIGH_GAIT_DRIVE_SCALE}" \
  --probe-adaptive-medium-posture-leg-target-offset "${PROBE_ADAPTIVE_MEDIUM_POSTURE_LEG_TARGET_OFFSET}" \
  --probe-adaptive-high-posture-leg-target-offset "${PROBE_ADAPTIVE_HIGH_POSTURE_LEG_TARGET_OFFSET}" \
  --settle-steps "${SETTLE_STEPS}" \
  --ramp-steps "${RAMP_STEPS}" \
  --stance-half-length "${STANCE_HALF_LENGTH}" \
  --stance-half-width "${STANCE_HALF_WIDTH}" \
  --foot-length "${FOOT_LENGTH}" \
  --foot-width "${FOOT_WIDTH}" \
  --foot-height "${FOOT_HEIGHT}" \
  --foot-mass "${FOOT_MASS}" \
  --foot-contact-z-threshold "${FOOT_CONTACT_Z_THRESHOLD}" \
  --stance-foot-latch-lift-threshold "${STANCE_FOOT_LATCH_LIFT_THRESHOLD}" \
  --leg-target "${LEG_TARGET}" \
  --leg-lower "${LEG_LOWER}" \
  --leg-upper "${LEG_UPPER}" \
  --leg-stiffness "${LEG_STIFFNESS}" \
  --leg-damping "${LEG_DAMPING}" \
  --leg-max-force "${LEG_MAX_FORCE}" \
  --balance-roll-gain "${BALANCE_ROLL_GAIN}" \
  --balance-pitch-gain "${BALANCE_PITCH_GAIN}" \
  --balance-max-correction "${BALANCE_MAX_CORRECTION}" \
  --x-slide-limit "${X_SLIDE_LIMIT}" \
  --x-slide-stiffness "${X_SLIDE_STIFFNESS}" \
  --x-slide-damping "${X_SLIDE_DAMPING}" \
  --x-slide-max-force "${X_SLIDE_MAX_FORCE}" \
  --swing-x-force-scale "${SWING_X_FORCE_SCALE}" \
  --static-friction "${STATIC_FRICTION}" \
  --dynamic-friction "${DYNAMIC_FRICTION}" \
  --fall-z "${FALL_Z}" \
  --drop-z "${DROP_Z}" \
  --max-stand-drift "${MAX_STAND_DRIFT}" \
  --output-dir "${OUTPUT_DIR}" \
  "${EXTRA_ARGS[@]}" \
  2>&1 | tee "${LOG_PATH}"

echo "[INFO] Log: ${LOG_PATH}"
echo "[INFO] Output: ${OUTPUT_DIR}"
