#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run G1 low-carry follow-up suite on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
cd "${ROOT_DIR}"

CASE_SET="${CASE_SET:-all}"
BASE_STAMP_PREFIX="${BASE_STAMP_PREFIX:-${FOLLOWUP_PREFIX:-$(date +%Y%m%d_g1_lowcarry_followup)}}"

run_lowcarry_case() {
  local case_name="$1"
  (
    export SUITE_STAMP="${BASE_STAMP_PREFIX}_${case_name}"
    export RUN_NOBOX=0 RUN_FIXED=0 RUN_FREE=1 STRICT=0 DEVICE=cpu
    export COMPUTE_SIDE_STARTUP_SLEEP="${COMPUTE_SIDE_STARTUP_SLEEP:-0}"
    export TARGET_X=-1.2 TARGET_Y=0.0
    export TARGET_WINDOW_CENTER=2.0 TARGET_WINDOW_HALFWIDTH=0.35
    export FREE_STEPS=819
    export FREE_BOX_MASS=0.25
    export FREE_BOX_SIZE_X=0.14 FREE_BOX_SIZE_Y=0.10 FREE_BOX_SIZE_Z=0.08
    export FREE_BOX_POS_X=-0.18
    export FREE_CRADLE_LOCAL_X=-0.18 FREE_CRADLE_LOCAL_Z=0.00
    export LARGERBOX_STRICT_MODE=lowcarry

    export AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL=0.18
    export AGILE_COMMAND_HOLD_SCALE=0.35
    export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=0.65
    export AGILE_COMMAND_HOLD_TERMINAL_LATCH=1
    export AGILE_COMMAND_HOLD_TERMINAL_MIN_STEP=420
    export AGILE_COMMAND_HOLD_TERMINAL_SCALE=0.015
    export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=0.6
    export AGILE_COMMAND_HOLD_FINAL_LATCH=1
    export AGILE_COMMAND_HOLD_FINAL_MIN_STEP=420
    export AGILE_COMMAND_HOLD_FINAL_SCALE=0.0

    export AGILE_COMMAND_HOLD_ADAPTIVE_SCALE=1
    export AGILE_COMMAND_HOLD_ADAPTIVE_MIN_SCALE=0.10
    export AGILE_COMMAND_HOLD_ADAPTIVE_MAX_SCALE=0.35
    export AGILE_COMMAND_HOLD_ADAPTIVE_TILT_START=0.14
    export AGILE_COMMAND_HOLD_ADAPTIVE_TILT_STOP=0.35
    export AGILE_COMMAND_HOLD_ADAPTIVE_RATE_START=2.0
    export AGILE_COMMAND_HOLD_ADAPTIVE_RATE_STOP=7.0
    export AGILE_COMMAND_HOLD_ADAPTIVE_REL_START=0.10
    export AGILE_COMMAND_HOLD_ADAPTIVE_REL_STOP=0.26
    export AGILE_COMMAND_HOLD_ADAPTIVE_SCALE_SMOOTHING=0.25
    export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT=1
    export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_START=0.12
    export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_STOP=0.35
    export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_START=2.0
    export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_STOP=7.0

    export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=1
    export AGILE_COMMAND_HOLD_LATERAL_ERROR_START=0.20
    export AGILE_COMMAND_HOLD_LATERAL_GAIN=0.006
    export AGILE_COMMAND_HOLD_LATERAL_LIMIT=0.0015
    export AGILE_COMMAND_HOLD_LATERAL_SIGN=-1.0
    export AGILE_COMMAND_HOLD_LATERAL_USE_EXCESS_ERROR=1
    export AGILE_COMMAND_HOLD_LATERAL_MAX_TILT=0.80
    export AGILE_COMMAND_HOLD_LATERAL_MAX_BOX_TILT=0.90
    export AGILE_COMMAND_HOLD_YAW_CORRECTION=1
    export AGILE_COMMAND_HOLD_YAW_GAIN=0.0
    export AGILE_COMMAND_HOLD_YAW_LIMIT=0.0
    export AGILE_COMMAND_HOLD_YAW_SIGN=-1.0

    export BALANCE_FEEDBACK_CONTROLLER=1
    export BALANCE_FEEDBACK_BASE=command
    export BALANCE_ADJUSTMENT_LIMIT=0.08
    export BALANCE_PITCH_GAIN=0.10
    export BALANCE_PITCH_RATE_GAIN=0.006
    export BALANCE_PITCH_SIGN=1.0
    export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.05
    export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.20
    export BALANCE_ROLL_GAIN=0.06
    export BALANCE_ROLL_RATE_GAIN=0.003
    export BALANCE_ROLL_SIGN=-1.0
    export BALANCE_ROLL_LEFT_ANKLE_SCALE=1.0
    export BALANCE_ROLL_RIGHT_ANKLE_SCALE=-1.0
    export BALANCE_ROLL_LEFT_HIP_SCALE=-0.5
    export BALANCE_ROLL_RIGHT_HIP_SCALE=0.5
    export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.05
    export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.20
    export BALANCE_START_ON_AGILE_HOLD=1

    export CRADLE_TOP_LID_ENABLED=1
    export CRADLE_TOP_LID_ENABLE_ON_HOLD=0
    export CRADLE_TOP_LID_LOCAL_Z=0.10
    export CRADLE_TOP_LID_THICKNESS=0.018
    export CRADLE_TOP_LID_X_SCALE=1.25
    export CRADLE_TOP_LID_Y_SCALE=1.25
    export CRADLE_SIDE_RAIL_HEIGHT=0.16
    export CRADLE_END_STOP_HEIGHT=0.18
    export CRADLE_RAIL_THICKNESS=0.03
    export CRADLE_CHEST_PAD_ENABLED=0
    export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0

    export FREE_MIN_ROBOT_TRAVEL=0.02 FREE_MIN_BOX_TRAVEL=0.02
    export FREE_MAX_TILT=0.35 FREE_MAX_BOX_TILT=0.45
    export FREE_MAX_ROBOT_LATERAL_ERROR=0.80
    export FREE_MAX_BOX_LATERAL_ERROR=0.80
    export FREE_MAX_FINAL_ROBOT_LATERAL_ERROR=0.60
    export FREE_MAX_FINAL_BOX_LATERAL_ERROR=0.60
    export FREE_MAX_FINAL_REL=0.25
    export FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL=2.35
    export FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL=2.35
    export MIN_FINAL_HOLD_ROBOT_Z=0.45
    export MIN_FINAL_HOLD_BOX_Z=0.45
    export MIN_AGILE_COMMAND_HOLD_FINAL_ACTIVE_STEPS=399
    export MIN_TARGET_WINDOW_BOTH_STABLE_STEPS=80
    export MIN_TARGET_WINDOW_BOTH_LONGEST_STREAK_STEPS=50
    export MIN_TARGET_WINDOW_BOTH_STREAK_AT_END_STEPS=40
    export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STABLE_STEPS=80
    export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_LONGEST_STREAK_STEPS=50
    export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STREAK_AT_END_STEPS=40

    case "${case_name}" in
      rollpos_delay)
        export BALANCE_ROLL_SIGN=1.0
        export BALANCE_START_STEP=420
        ;;
      chestpad_hold_contact)
        export CRADLE_CHEST_PAD_ENABLED=1
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=1
        export CRADLE_CHEST_PAD_LOCAL_X=-0.02
        export CRADLE_CHEST_PAD_LOCAL_Z=0.10
        export CRADLE_CHEST_PAD_SIZE_X=0.04
        export CRADLE_CHEST_PAD_SIZE_Y=0.38
        export CRADLE_CHEST_PAD_SIZE_Z=0.22
        ;;
      chestpad_terminal_contact)
        export CRADLE_CHEST_PAD_ENABLED=1
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=1
        export CRADLE_CHEST_PAD_LOCAL_X=-0.02
        export CRADLE_CHEST_PAD_LOCAL_Z=0.10
        export CRADLE_CHEST_PAD_SIZE_X=0.04
        export CRADLE_CHEST_PAD_SIZE_Y=0.38
        export CRADLE_CHEST_PAD_SIZE_Z=0.22
        ;;
      chestpad_terminal_nolateral)
        export CRADLE_CHEST_PAD_ENABLED=1
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=1
        export CRADLE_CHEST_PAD_LOCAL_X=-0.02
        export CRADLE_CHEST_PAD_LOCAL_Z=0.10
        export CRADLE_CHEST_PAD_SIZE_X=0.04
        export CRADLE_CHEST_PAD_SIZE_Y=0.38
        export CRADLE_CHEST_PAD_SIZE_Z=0.22
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        ;;
      chestpad_terminal_tiny_pad)
        export CRADLE_CHEST_PAD_ENABLED=1
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=1
        export CRADLE_CHEST_PAD_LOCAL_X=-0.05
        export CRADLE_CHEST_PAD_LOCAL_Z=0.10
        export CRADLE_CHEST_PAD_SIZE_X=0.018
        export CRADLE_CHEST_PAD_SIZE_Y=0.26
        export CRADLE_CHEST_PAD_SIZE_Z=0.12
        ;;
      chestpad_terminal_late_tiny_pad)
        export CRADLE_CHEST_PAD_ENABLED=1
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=1
        export CRADLE_CHEST_PAD_LOCAL_X=-0.05
        export CRADLE_CHEST_PAD_LOCAL_Z=0.10
        export CRADLE_CHEST_PAD_SIZE_X=0.018
        export CRADLE_CHEST_PAD_SIZE_Y=0.26
        export CRADLE_CHEST_PAD_SIZE_Z=0.12
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=1.20
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=1.15
        ;;
      nopad_final_freeze)
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_IN_TARGET_WINDOW=1
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_TILT=0.30
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_BOX_TILT=0.42
        export AGILE_COMMAND_HOLD_FINAL_RESET_POLICY_STATE=1
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.10
        export BALANCE_PITCH_GAIN=0.12
        export BALANCE_PITCH_RATE_GAIN=0.008
        export BALANCE_ROLL_GAIN=0.08
        export BALANCE_ROLL_RATE_GAIN=0.004
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      nopad_stronger_balance)
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.12
        export BALANCE_PITCH_GAIN=0.16
        export BALANCE_PITCH_RATE_GAIN=0.012
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.035
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.12
        export BALANCE_ROLL_GAIN=0.10
        export BALANCE_ROLL_RATE_GAIN=0.006
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.035
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.12
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      nopad_late_gentle_rescue)
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_IN_TARGET_WINDOW=1
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_TILT=0.24
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_BOX_TILT=0.40
        export AGILE_COMMAND_HOLD_FINAL_RESET_POLICY_STATE=1
        export AGILE_COMMAND_HOLD_RESCUE_ENABLE=1
        export AGILE_COMMAND_HOLD_RESCUE_FORWARD_PITCH_THRESHOLD=-0.42
        export AGILE_COMMAND_HOLD_RESCUE_ABS_ROLL_THRESHOLD=0.32
        export AGILE_COMMAND_HOLD_RESCUE_BLEND_RATE=0.008
        export AGILE_COMMAND_HOLD_RESCUE_HIP_PITCH=-0.08
        export AGILE_COMMAND_HOLD_RESCUE_KNEE=0.32
        export AGILE_COMMAND_HOLD_RESCUE_ANKLE_PITCH=-0.16
        export AGILE_COMMAND_HOLD_RESCUE_WAIST_PITCH=-0.02
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.09
        export BALANCE_PITCH_GAIN=0.12
        export BALANCE_PITCH_RATE_GAIN=0.008
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.04
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.14
        export BALANCE_ROLL_GAIN=0.08
        export BALANCE_ROLL_RATE_GAIN=0.004
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.04
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.14
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      nopad_late_stand_blend)
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export AGILE_COMMAND_HOLD_MODE=policy_then_stand
        export AGILE_COMMAND_HOLD_POLICY_THEN_STAND_DELAY_STEPS=300
        export AGILE_COMMAND_HOLD_STAND_BLEND_RATE=0.006
        export AGILE_COMMAND_HOLD_STAND_HIP_PITCH=-0.04
        export AGILE_COMMAND_HOLD_STAND_KNEE=0.28
        export AGILE_COMMAND_HOLD_STAND_ANKLE_PITCH=-0.14
        export AGILE_COMMAND_HOLD_STAND_WAIST_PITCH=-0.02
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_IN_TARGET_WINDOW=1
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_TILT=0.24
        export AGILE_COMMAND_HOLD_FINAL_FREEZE_MAX_BOX_TILT=0.40
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.09
        export BALANCE_PITCH_GAIN=0.12
        export BALANCE_PITCH_RATE_GAIN=0.008
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.04
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.14
        export BALANCE_ROLL_GAIN=0.08
        export BALANCE_ROLL_RATE_GAIN=0.004
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.04
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.14
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      load05_window_zero_arrest)
        export FREE_BOX_MASS=0.50
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=0.58
        export AGILE_COMMAND_HOLD_TERMINAL_SCALE=0.010
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=0.52
        export AGILE_COMMAND_HOLD_FINAL_SCALE=0.0
        export AGILE_COMMAND_HOLD_FINAL_ZERO_CORRECTIONS=1
        export AGILE_COMMAND_HOLD_FINAL_RESET_POLICY_STATE=1
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.07
        export BALANCE_PITCH_GAIN=0.09
        export BALANCE_PITCH_RATE_GAIN=0.005
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.06
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.20
        export BALANCE_ROLL_GAIN=0.05
        export BALANCE_ROLL_RATE_GAIN=0.003
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.06
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.20
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      load05_window_reverse_brake)
        export FREE_BOX_MASS=0.50
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=0.58
        export AGILE_COMMAND_HOLD_TERMINAL_SCALE=0.010
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=0.52
        export AGILE_COMMAND_HOLD_FINAL_SCALE=0.0
        export AGILE_COMMAND_HOLD_FINAL_ZERO_CORRECTIONS=1
        export AGILE_COMMAND_HOLD_FINAL_RESET_POLICY_STATE=1
        export AGILE_COMMAND_HOLD_FINAL_BRAKE_COMMAND_X=0.006
        export AGILE_COMMAND_HOLD_FINAL_BRAKE_DELAY_STEPS=0
        export AGILE_COMMAND_HOLD_FINAL_BRAKE_STEPS=140
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.07
        export BALANCE_PITCH_GAIN=0.09
        export BALANCE_PITCH_RATE_GAIN=0.005
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.06
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.20
        export BALANCE_ROLL_GAIN=0.05
        export BALANCE_ROLL_RATE_GAIN=0.003
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.06
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.20
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      load05_box_progress_pd)
        export FREE_BOX_MASS=0.50
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_SCALE=1.0
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_BOX_PROGRESS_CONTROLLER=1
        export AGILE_COMMAND_BOX_PROGRESS_START_STEP=40
        export AGILE_COMMAND_BOX_PROGRESS_TARGET=2.0
        export AGILE_COMMAND_BOX_PROGRESS_DEADBAND=0.08
        export AGILE_COMMAND_BOX_PROGRESS_GAIN=0.08
        export AGILE_COMMAND_BOX_PROGRESS_MAX_FORWARD=0.10
        export AGILE_COMMAND_BOX_PROGRESS_MAX_REVERSE=0.035
        export AGILE_COMMAND_BOX_PROGRESS_MAX_TILT=0.40
        export AGILE_COMMAND_BOX_PROGRESS_MAX_BOX_TILT=0.55
        export AGILE_COMMAND_BOX_LATERAL_CONTROLLER=1
        export AGILE_COMMAND_BOX_LATERAL_DEADBAND=0.12
        export AGILE_COMMAND_BOX_LATERAL_GAIN=0.012
        export AGILE_COMMAND_BOX_LATERAL_LIMIT=0.002
        export AGILE_COMMAND_BOX_LATERAL_SIGN=1.0
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.08
        export BALANCE_PITCH_GAIN=0.10
        export BALANCE_PITCH_RATE_GAIN=0.006
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.05
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_GAIN=0.06
        export BALANCE_ROLL_RATE_GAIN=0.003
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.05
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      load05_box_progress_conservative)
        export FREE_BOX_MASS=0.50
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_SCALE=1.0
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_BOX_PROGRESS_CONTROLLER=1
        export AGILE_COMMAND_BOX_PROGRESS_START_STEP=40
        export AGILE_COMMAND_BOX_PROGRESS_TARGET=2.0
        export AGILE_COMMAND_BOX_PROGRESS_DEADBAND=0.10
        export AGILE_COMMAND_BOX_PROGRESS_GAIN=0.055
        export AGILE_COMMAND_BOX_PROGRESS_MAX_FORWARD=0.075
        export AGILE_COMMAND_BOX_PROGRESS_MAX_REVERSE=0.025
        export AGILE_COMMAND_BOX_PROGRESS_MAX_TILT=0.35
        export AGILE_COMMAND_BOX_PROGRESS_MAX_BOX_TILT=0.48
        export AGILE_COMMAND_BOX_LATERAL_CONTROLLER=1
        export AGILE_COMMAND_BOX_LATERAL_DEADBAND=0.14
        export AGILE_COMMAND_BOX_LATERAL_GAIN=0.010
        export AGILE_COMMAND_BOX_LATERAL_LIMIT=0.0015
        export AGILE_COMMAND_BOX_LATERAL_SIGN=1.0
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.07
        export BALANCE_PITCH_GAIN=0.09
        export BALANCE_PITCH_RATE_GAIN=0.005
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.05
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_GAIN=0.05
        export BALANCE_ROLL_RATE_GAIN=0.003
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.05
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      load05_box_progress_retention)
        export FREE_BOX_MASS=0.50
        export CRADLE_CHEST_PAD_ENABLED=0
        export CRADLE_CHEST_PAD_ENABLE_ON_HOLD=0
        export CRADLE_CHEST_PAD_ENABLE_ON_TERMINAL_HOLD=0
        export AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_SCALE=1.0
        export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=-1.0
        export AGILE_COMMAND_BOX_PROGRESS_CONTROLLER=1
        export AGILE_COMMAND_BOX_PROGRESS_START_STEP=40
        export AGILE_COMMAND_BOX_PROGRESS_TARGET=2.0
        export AGILE_COMMAND_BOX_PROGRESS_DEADBAND=0.09
        export AGILE_COMMAND_BOX_PROGRESS_GAIN=0.065
        export AGILE_COMMAND_BOX_PROGRESS_MAX_FORWARD=0.085
        export AGILE_COMMAND_BOX_PROGRESS_MAX_REVERSE=0.030
        export AGILE_COMMAND_BOX_PROGRESS_MAX_TILT=0.38
        export AGILE_COMMAND_BOX_PROGRESS_MAX_BOX_TILT=0.52
        export AGILE_COMMAND_BOX_LATERAL_CONTROLLER=1
        export AGILE_COMMAND_BOX_LATERAL_DEADBAND=0.12
        export AGILE_COMMAND_BOX_LATERAL_GAIN=0.010
        export AGILE_COMMAND_BOX_LATERAL_LIMIT=0.0015
        export AGILE_COMMAND_BOX_LATERAL_SIGN=1.0
        export BOX_RETENTION_POSTURE_CONTROLLER=1
        export BOX_RETENTION_REL_START=0.08
        export BOX_RETENTION_REL_STOP=0.24
        export BOX_RETENTION_TILT_START=0.16
        export BOX_RETENTION_TILT_STOP=0.45
        export BOX_RETENTION_HIP_PITCH_OFFSET=-0.035
        export BOX_RETENTION_KNEE_OFFSET=0.10
        export BOX_RETENTION_ANKLE_PITCH_OFFSET=-0.05
        export BOX_RETENTION_WAIST_PITCH_OFFSET=-0.025
        export BOX_RETENTION_SHOULDER_PITCH_OFFSET=-0.08
        export BOX_RETENTION_ELBOW_OFFSET=0.14
        export BOX_RETENTION_WRIST_PITCH_OFFSET=-0.035
        export AGILE_COMMAND_HOLD_LATERAL_CORRECTION=0
        export AGILE_COMMAND_HOLD_YAW_CORRECTION=0
        export BALANCE_START_STEP=420
        export BALANCE_ADJUSTMENT_LIMIT=0.07
        export BALANCE_PITCH_GAIN=0.09
        export BALANCE_PITCH_RATE_GAIN=0.005
        export BALANCE_PITCH_ACTIVATION_THRESHOLD=0.05
        export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_GAIN=0.05
        export BALANCE_ROLL_RATE_GAIN=0.003
        export BALANCE_ROLL_ACTIVATION_THRESHOLD=0.05
        export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD=0.18
        export BALANCE_ROLL_SIGN=-1.0
        ;;
      *)
        echo "Unknown low-carry follow-up case: ${case_name}" >&2
        exit 2
        ;;
    esac

    scripts/isaac/run_core_world_g1_agile_policy_low_cradle_suite.sh
  )
}

run_roll_delay() {
  run_lowcarry_case "rollpos_delay"
}

run_contact_chestpad() {
  run_lowcarry_case "chestpad_hold_contact"
}

run_contact_chestpad_terminal() {
  run_lowcarry_case "chestpad_terminal_contact"
}

run_contact_rescue() {
  run_lowcarry_case "chestpad_terminal_nolateral"
  run_lowcarry_case "chestpad_terminal_tiny_pad"
  run_lowcarry_case "chestpad_terminal_late_tiny_pad"
}

run_balance_rescue() {
  run_lowcarry_case "nopad_final_freeze"
  run_lowcarry_case "nopad_stronger_balance"
}

run_late_recovery() {
  run_lowcarry_case "nopad_late_gentle_rescue"
  run_lowcarry_case "nopad_late_stand_blend"
}

run_target_window_arrest() {
  run_lowcarry_case "load05_window_zero_arrest"
  run_lowcarry_case "load05_window_reverse_brake"
}

run_box_progress_controller() {
  run_lowcarry_case "load05_box_progress_pd"
  run_lowcarry_case "load05_box_progress_conservative"
}

run_box_progress_retention() {
  run_lowcarry_case "load05_box_progress_retention"
}

case "${CASE_SET}" in
  all)
    run_roll_delay
    run_contact_chestpad
    ;;
  roll)
    run_roll_delay
    ;;
  contact)
    run_contact_chestpad
    ;;
  contact_terminal|contact_next)
    run_contact_chestpad_terminal
    ;;
  contact_rescue)
    run_contact_rescue
    ;;
  balance_rescue)
    run_balance_rescue
    ;;
  late_recovery)
    run_late_recovery
    ;;
  target_window_arrest)
    run_target_window_arrest
    ;;
  box_progress_controller)
    run_box_progress_controller
    ;;
  box_progress_retention)
    run_box_progress_retention
    ;;
  *)
    echo "Unknown CASE_SET=${CASE_SET}; expected all, roll, contact, contact_terminal, contact_next, contact_rescue, balance_rescue, late_recovery, target_window_arrest, box_progress_controller, or box_progress_retention" >&2
    exit 2
    ;;
esac
