#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run active-probe posture sweep on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
ISAAC_VENV="${ISAAC_VENV:-/public/home/yanhongru/envs/isaac_arena_py312}"
STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)_task_runner_active_probe_postures}"
BOX_SEED="${BOX_SEED:-7080}"
TARGET_X="${TARGET_X:-0.64}"
STEPS="${STEPS:-3660}"
SUPPORT_MODE="${SUPPORT_MODE:-alternating_anchor_feet}"
STEP_LENGTH="${STEP_LENGTH:-}"
STANCE_STEPS="${STANCE_STEPS:-80}"
GAIT_SPEED_SCALE="${GAIT_SPEED_SCALE:-1.0}"
FEEDBACK_STEP_X_GAIN="${FEEDBACK_STEP_X_GAIN:-0.015}"
FEEDBACK_STEP_X_LIMIT="${FEEDBACK_STEP_X_LIMIT:-0.008}"
FEEDBACK_STEP_TILT_GAIN="${FEEDBACK_STEP_TILT_GAIN:-0.05}"
FEEDBACK_STEP_TILT_LIMIT="${FEEDBACK_STEP_TILT_LIMIT:-0.005}"
SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION="${SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION:-0.18}"
STANCE_FOOT_WORLD_LOCK="${STANCE_FOOT_WORLD_LOCK:-0}"
FREEZE_LOCKED_STANCE_FOOT_TARGETS="${FREEZE_LOCKED_STANCE_FOOT_TARGETS:-0}"
FREEZE_COMMANDED_STANCE_FOOT_TARGETS="${FREEZE_COMMANDED_STANCE_FOOT_TARGETS:-0}"
PLANTED_STANCE_RAIL_PROPULSION="${PLANTED_STANCE_RAIL_PROPULSION:-0}"
SUPPORT_FOOT_DRIVE_STIFFNESS="${SUPPORT_FOOT_DRIVE_STIFFNESS:-}"
SUPPORT_FOOT_DRIVE_DAMPING="${SUPPORT_FOOT_DRIVE_DAMPING:-}"
SUPPORT_FOOT_DRIVE_MAX_FORCE="${SUPPORT_FOOT_DRIVE_MAX_FORCE:-}"
SUPPORT_FOOT_Z_DRIVE_STIFFNESS="${SUPPORT_FOOT_Z_DRIVE_STIFFNESS:-}"
SUPPORT_FOOT_Z_DRIVE_DAMPING="${SUPPORT_FOOT_Z_DRIVE_DAMPING:-}"
SUPPORT_FOOT_Z_DRIVE_MAX_FORCE="${SUPPORT_FOOT_Z_DRIVE_MAX_FORCE:-}"
STATIC_FRICTION="${STATIC_FRICTION:-}"
DYNAMIC_FRICTION="${DYNAMIC_FRICTION:-}"
PROBE_STEPS="${PROBE_STEPS:-80}"
PROBE_AMPLITUDE_X="${PROBE_AMPLITUDE_X:-0.012}"
PROBE_AMPLITUDE_Z="${PROBE_AMPLITUDE_Z:-0.0}"
POSTURES="${POSTURES:-front_mid low_front chest_high}"
SUMMARY_OUTPUT="${SUMMARY_OUTPUT:-${ROOT_DIR}/experiments/outputs/direct_carry_task_runner_active_probe_postures/${STAMP}/active_probe_posture_summary.json}"

if [[ "${SUPPORT_MODE}" == "alternating_placement_feet" ]]; then
  DEFAULT_CONTROLLER_MODE="physical_alternating_placement_feet_cradle"
  DEFAULT_REQUIRE_DIRECTIONAL_FOOT_PLACEMENT="1"
else
  DEFAULT_CONTROLLER_MODE="physical_alternating_anchor_feet_cradle"
  DEFAULT_REQUIRE_DIRECTIONAL_FOOT_PLACEMENT="0"
fi
CONTROLLER_MODE="${CONTROLLER_MODE:-${DEFAULT_CONTROLLER_MODE}}"
REQUIRE_DIRECTIONAL_FOOT_PLACEMENT="${REQUIRE_DIRECTIONAL_FOOT_PLACEMENT:-${DEFAULT_REQUIRE_DIRECTIONAL_FOOT_PLACEMENT}}"
SUPPORT_FOOT_PLACEMENT_MODE="${SUPPORT_FOOT_PLACEMENT_MODE:-alternating_directional_x}"

cd "${ROOT_DIR}"
mkdir -p "$(dirname "${SUMMARY_OUTPUT}")" logs/direct_carry_task_runner

failed=0
for posture in ${POSTURES}; do
  case_stamp="${STAMP}_${posture}"
  echo "[CASE] posture=${posture} case_stamp=${case_stamp} box_seed=${BOX_SEED}"
  set +e
  STAMP="${case_stamp}" \
    BOX_SEED="${BOX_SEED}" \
    CARRY_POSTURE="${posture}" \
    TARGET_X="${TARGET_X}" \
    STEPS="${STEPS}" \
    SUPPORT_MODE="${SUPPORT_MODE}" \
    STEP_LENGTH="${STEP_LENGTH}" \
    STANCE_STEPS="${STANCE_STEPS}" \
    GAIT_SPEED_SCALE="${GAIT_SPEED_SCALE}" \
    FEEDBACK_STEP_X_GAIN="${FEEDBACK_STEP_X_GAIN}" \
    FEEDBACK_STEP_X_LIMIT="${FEEDBACK_STEP_X_LIMIT}" \
    FEEDBACK_STEP_TILT_GAIN="${FEEDBACK_STEP_TILT_GAIN}" \
    FEEDBACK_STEP_TILT_LIMIT="${FEEDBACK_STEP_TILT_LIMIT}" \
    SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION="${SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION}" \
    STANCE_FOOT_WORLD_LOCK="${STANCE_FOOT_WORLD_LOCK}" \
    FREEZE_LOCKED_STANCE_FOOT_TARGETS="${FREEZE_LOCKED_STANCE_FOOT_TARGETS}" \
    FREEZE_COMMANDED_STANCE_FOOT_TARGETS="${FREEZE_COMMANDED_STANCE_FOOT_TARGETS}" \
    PLANTED_STANCE_RAIL_PROPULSION="${PLANTED_STANCE_RAIL_PROPULSION}" \
    SUPPORT_FOOT_DRIVE_STIFFNESS="${SUPPORT_FOOT_DRIVE_STIFFNESS}" \
    SUPPORT_FOOT_DRIVE_DAMPING="${SUPPORT_FOOT_DRIVE_DAMPING}" \
    SUPPORT_FOOT_DRIVE_MAX_FORCE="${SUPPORT_FOOT_DRIVE_MAX_FORCE}" \
    SUPPORT_FOOT_Z_DRIVE_STIFFNESS="${SUPPORT_FOOT_Z_DRIVE_STIFFNESS}" \
    SUPPORT_FOOT_Z_DRIVE_DAMPING="${SUPPORT_FOOT_Z_DRIVE_DAMPING}" \
    SUPPORT_FOOT_Z_DRIVE_MAX_FORCE="${SUPPORT_FOOT_Z_DRIVE_MAX_FORCE}" \
    STATIC_FRICTION="${STATIC_FRICTION}" \
    DYNAMIC_FRICTION="${DYNAMIC_FRICTION}" \
    PROBE_STEPS="${PROBE_STEPS}" \
    PROBE_AMPLITUDE_X="${PROBE_AMPLITUDE_X}" \
    PROBE_AMPLITUDE_Z="${PROBE_AMPLITUDE_Z}" \
    bash scripts/isaac/run_direct_carry_task_runner_episode.sh
  run_status=$?
  set -e
  echo "[CASE_STATUS] posture=${posture} run_status=${run_status}"
  if [[ "${run_status}" -ne 0 ]]; then
    failed=1
    continue
  fi

  set +e
  STAMP="${case_stamp}_probecheck" \
    SUMMARY="experiments/outputs/direct_carry_task_runner/${case_stamp}/direct_carry_task_physical_backend_summary.json" \
    BOX_SEED="${BOX_SEED}" \
    CARRY_POSTURE="${posture}" \
    CONTROLLER_MODE="${CONTROLLER_MODE}" \
    MIN_STEPS="${STEPS}" \
    REQUIRE_PROBE_BELIEF=1 \
    MIN_PROBE_STEPS="${PROBE_STEPS}" \
    MIN_PROBE_BOX_TRAVEL_X="${MIN_PROBE_BOX_TRAVEL_X:-0.01}" \
    REQUIRE_DIRECTIONAL_FOOT_PLACEMENT="${REQUIRE_DIRECTIONAL_FOOT_PLACEMENT}" \
    SUPPORT_FOOT_PLACEMENT_MODE="${SUPPORT_FOOT_PLACEMENT_MODE}" \
    MIN_BOX_TRAVEL="${MIN_BOX_TRAVEL:-0.50}" \
    MIN_POST_SETTLE_BOX_TRAVEL_X="${MIN_POST_SETTLE_BOX_TRAVEL_X:-0.50}" \
    MIN_ABS_BOX_TRAVEL_X="${MIN_ABS_BOX_TRAVEL_X:-}" \
    MIN_ABS_POST_SETTLE_BOX_TRAVEL_X="${MIN_ABS_POST_SETTLE_BOX_TRAVEL_X:-}" \
    MAX_NEAR_GROUND_FOOT_SPEED="${MAX_NEAR_GROUND_FOOT_SPEED:-}" \
    MAX_NEAR_GROUND_FOOT_SLIP="${MAX_NEAR_GROUND_FOOT_SLIP:-}" \
    REQUIRE_STANCE_FOOT_WORLD_LOCK="${REQUIRE_STANCE_FOOT_WORLD_LOCK:-0}" \
    MIN_STANCE_FOOT_WORLD_LOCK_SWITCHES="${MIN_STANCE_FOOT_WORLD_LOCK_SWITCHES:-1}" \
    REQUIRE_FREEZE_LOCKED_STANCE_FOOT_TARGETS="${REQUIRE_FREEZE_LOCKED_STANCE_FOOT_TARGETS:-0}" \
    REQUIRE_FREEZE_COMMANDED_STANCE_FOOT_TARGETS="${REQUIRE_FREEZE_COMMANDED_STANCE_FOOT_TARGETS:-0}" \
    REQUIRE_PLANTED_STANCE_RAIL_PROPULSION="${REQUIRE_PLANTED_STANCE_RAIL_PROPULSION:-0}" \
    bash scripts/isaac/run_check_direct_carry_task_runner_episode.sh
  check_status=$?
  set -e
  echo "[CHECK_STATUS] posture=${posture} check_status=${check_status}"
  if [[ "${check_status}" -ne 0 ]]; then
    failed=1
  fi
done

"${ISAAC_VENV}/bin/python" scripts/isaac/summarize_task_runner_active_probe_postures.py \
  --stamp "${STAMP}" \
  --box-seed "${BOX_SEED}" \
  --output "${SUMMARY_OUTPUT}" \
  --postures ${POSTURES}

echo "[INFO] Active-probe posture summary: ${SUMMARY_OUTPUT}"
exit "${failed}"
