#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run G1 larger-box strict suite on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
MODE="${LARGERBOX_STRICT_MODE:-boxtilt}"

case "${MODE}" in
  boxtilt)
    DEFAULT_STAMP="20260706_g1_agile_adaptive_largerbox_boxtilt_strict_700_targetnegx1"
    export CRADLE_CHEST_PAD_ENABLED="${CRADLE_CHEST_PAD_ENABLED:-0}"
    export CRADLE_CHEST_PAD_ENABLE_ON_HOLD="${CRADLE_CHEST_PAD_ENABLE_ON_HOLD:-0}"
    ;;
  lowcarry)
    DEFAULT_STAMP="20260706_g1_agile_largerbox_lowcarry_strict_700_targetnegx1"
    export CRADLE_CHEST_PAD_ENABLED="${CRADLE_CHEST_PAD_ENABLED:-0}"
    export CRADLE_CHEST_PAD_ENABLE_ON_HOLD="${CRADLE_CHEST_PAD_ENABLE_ON_HOLD:-0}"
    export FREE_CRADLE_LOCAL_Z="${FREE_CRADLE_LOCAL_Z:-0.00}"
    export CRADLE_TOP_LID_LOCAL_Z="${CRADLE_TOP_LID_LOCAL_Z:-0.13}"
    export CRADLE_SIDE_RAIL_HEIGHT="${CRADLE_SIDE_RAIL_HEIGHT:-0.10}"
    export CRADLE_END_STOP_HEIGHT="${CRADLE_END_STOP_HEIGHT:-0.11}"
    ;;
  chestpad)
    DEFAULT_STAMP="20260706_g1_agile_largerbox_chestpad_strict_700_targetnegx1"
    export CRADLE_CHEST_PAD_ENABLED="${CRADLE_CHEST_PAD_ENABLED:-1}"
    export CRADLE_CHEST_PAD_ENABLE_ON_HOLD="${CRADLE_CHEST_PAD_ENABLE_ON_HOLD:-1}"
    ;;
  *)
    echo "Unknown LARGERBOX_STRICT_MODE=${MODE}; expected boxtilt, lowcarry, or chestpad" >&2
    exit 2
    ;;
esac

export SUITE_STAMP="${SUITE_STAMP:-${DEFAULT_STAMP}}"
export DEVICE="${DEVICE:-cpu}"
export STRICT="${STRICT:-0}"
export AGILE_POLICY_BACKEND="${AGILE_POLICY_BACKEND:-onnx}"
export RUN_NOBOX="${RUN_NOBOX:-0}"
export RUN_FIXED="${RUN_FIXED:-0}"
export RUN_FREE="${RUN_FREE:-1}"
export TARGET_X="${TARGET_X:--1.2}"
export TARGET_Y="${TARGET_Y:-0.0}"

export FREE_STEPS="${FREE_STEPS:-700}"
export FREE_BOX_MASS="${FREE_BOX_MASS:-0.5}"
export FREE_BOX_SIZE_X="${FREE_BOX_SIZE_X:-0.14}"
export FREE_BOX_SIZE_Y="${FREE_BOX_SIZE_Y:-0.10}"
export FREE_BOX_SIZE_Z="${FREE_BOX_SIZE_Z:-0.08}"
export FREE_BOX_POS_X="${FREE_BOX_POS_X:--0.18}"
export FREE_CRADLE_LOCAL_X="${FREE_CRADLE_LOCAL_X:--0.18}"
export FREE_CRADLE_LOCAL_Z="${FREE_CRADLE_LOCAL_Z:-0.05}"
export FREE_MIN_ROBOT_TRAVEL="${FREE_MIN_ROBOT_TRAVEL:-0.02}"
export FREE_MIN_BOX_TRAVEL="${FREE_MIN_BOX_TRAVEL:-0.02}"
export FREE_MAX_TILT="${FREE_MAX_TILT:-0.35}"
export FREE_MAX_BOX_TILT="${FREE_MAX_BOX_TILT:-0.45}"
export FREE_MAX_FINAL_REL="${FREE_MAX_FINAL_REL:-0.25}"
export FREE_MAX_ROBOT_LATERAL_ERROR="${FREE_MAX_ROBOT_LATERAL_ERROR:-0.80}"
export FREE_MAX_BOX_LATERAL_ERROR="${FREE_MAX_BOX_LATERAL_ERROR:-0.80}"
export FREE_MAX_FINAL_ROBOT_LATERAL_ERROR="${FREE_MAX_FINAL_ROBOT_LATERAL_ERROR:-0.60}"
export FREE_MAX_FINAL_BOX_LATERAL_ERROR="${FREE_MAX_FINAL_BOX_LATERAL_ERROR:-0.60}"
export FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL="${FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL:-}"
export FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL="${FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL:-}"

export AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL="${AGILE_COMMAND_STOP_BOX_TARGET_TRAVEL:-0.18}"
export AGILE_COMMAND_HOLD_SCALE="${AGILE_COMMAND_HOLD_SCALE:-0.35}"
export AGILE_COMMAND_HOLD_MODE="${AGILE_COMMAND_HOLD_MODE:-policy_command}"
export AGILE_COMMAND_HOLD_ADAPTIVE_SCALE="${AGILE_COMMAND_HOLD_ADAPTIVE_SCALE:-1}"
export AGILE_COMMAND_HOLD_ADAPTIVE_MIN_SCALE="${AGILE_COMMAND_HOLD_ADAPTIVE_MIN_SCALE:-0.10}"
export AGILE_COMMAND_HOLD_ADAPTIVE_MAX_SCALE="${AGILE_COMMAND_HOLD_ADAPTIVE_MAX_SCALE:-0.35}"
export AGILE_COMMAND_HOLD_ADAPTIVE_TILT_START="${AGILE_COMMAND_HOLD_ADAPTIVE_TILT_START:-0.14}"
export AGILE_COMMAND_HOLD_ADAPTIVE_TILT_STOP="${AGILE_COMMAND_HOLD_ADAPTIVE_TILT_STOP:-0.35}"
export AGILE_COMMAND_HOLD_ADAPTIVE_RATE_START="${AGILE_COMMAND_HOLD_ADAPTIVE_RATE_START:-2.0}"
export AGILE_COMMAND_HOLD_ADAPTIVE_RATE_STOP="${AGILE_COMMAND_HOLD_ADAPTIVE_RATE_STOP:-7.0}"
export AGILE_COMMAND_HOLD_ADAPTIVE_REL_START="${AGILE_COMMAND_HOLD_ADAPTIVE_REL_START:-0.10}"
export AGILE_COMMAND_HOLD_ADAPTIVE_REL_STOP="${AGILE_COMMAND_HOLD_ADAPTIVE_REL_STOP:-0.26}"
export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT="${AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT:-1}"
export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_START="${AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_START:-0.12}"
export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_STOP="${AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_STOP:-0.35}"
export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_START="${AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_START:-2.0}"
export AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_STOP="${AGILE_COMMAND_HOLD_ADAPTIVE_BOX_TILT_RATE_STOP:-7.0}"
export AGILE_COMMAND_HOLD_ADAPTIVE_SCALE_SMOOTHING="${AGILE_COMMAND_HOLD_ADAPTIVE_SCALE_SMOOTHING:-0.25}"
export AGILE_COMMAND_HOLD_LATERAL_CORRECTION="${AGILE_COMMAND_HOLD_LATERAL_CORRECTION:-1}"
export AGILE_COMMAND_HOLD_LATERAL_GAIN="${AGILE_COMMAND_HOLD_LATERAL_GAIN:-0.08}"
export AGILE_COMMAND_HOLD_LATERAL_LIMIT="${AGILE_COMMAND_HOLD_LATERAL_LIMIT:-0.035}"
export AGILE_COMMAND_HOLD_LATERAL_SIGN="${AGILE_COMMAND_HOLD_LATERAL_SIGN:-1.0}"
export AGILE_COMMAND_HOLD_YAW_CORRECTION="${AGILE_COMMAND_HOLD_YAW_CORRECTION:-0}"

export BALANCE_FEEDBACK_CONTROLLER="${BALANCE_FEEDBACK_CONTROLLER:-1}"
export BALANCE_START_ON_AGILE_HOLD="${BALANCE_START_ON_AGILE_HOLD:-1}"
export BALANCE_FEEDBACK_BASE="${BALANCE_FEEDBACK_BASE:-command}"
export BALANCE_PITCH_SIGN="${BALANCE_PITCH_SIGN:-1.0}"
export BALANCE_PITCH_GAIN="${BALANCE_PITCH_GAIN:-0.10}"
export BALANCE_PITCH_RATE_GAIN="${BALANCE_PITCH_RATE_GAIN:-0.006}"
export BALANCE_ROLL_GAIN="${BALANCE_ROLL_GAIN:-0.06}"
export BALANCE_ROLL_RATE_GAIN="${BALANCE_ROLL_RATE_GAIN:-0.003}"
export BALANCE_ADJUSTMENT_LIMIT="${BALANCE_ADJUSTMENT_LIMIT:-0.08}"
export BALANCE_ROLL_LEFT_ANKLE_SCALE="${BALANCE_ROLL_LEFT_ANKLE_SCALE:-1.0}"
export BALANCE_ROLL_RIGHT_ANKLE_SCALE="${BALANCE_ROLL_RIGHT_ANKLE_SCALE:--1.0}"
export BALANCE_ROLL_LEFT_HIP_SCALE="${BALANCE_ROLL_LEFT_HIP_SCALE:--0.5}"
export BALANCE_ROLL_RIGHT_HIP_SCALE="${BALANCE_ROLL_RIGHT_HIP_SCALE:-0.5}"
export BALANCE_PITCH_ACTIVATION_THRESHOLD="${BALANCE_PITCH_ACTIVATION_THRESHOLD:-0.05}"
export BALANCE_ROLL_ACTIVATION_THRESHOLD="${BALANCE_ROLL_ACTIVATION_THRESHOLD:-0.05}"
export BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD="${BALANCE_PITCH_RATE_ACTIVATION_THRESHOLD:-0.20}"
export BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD="${BALANCE_ROLL_RATE_ACTIVATION_THRESHOLD:-0.20}"

export CRADLE_TOP_LID_ENABLED="${CRADLE_TOP_LID_ENABLED:-1}"
export CRADLE_TOP_LID_ENABLE_ON_HOLD="${CRADLE_TOP_LID_ENABLE_ON_HOLD:-1}"
export CRADLE_TOP_LID_LOCAL_Z="${CRADLE_TOP_LID_LOCAL_Z:-0.16}"
export CRADLE_TOP_LID_THICKNESS="${CRADLE_TOP_LID_THICKNESS:-0.014}"
export CRADLE_TOP_LID_X_SCALE="${CRADLE_TOP_LID_X_SCALE:-1.15}"
export CRADLE_TOP_LID_Y_SCALE="${CRADLE_TOP_LID_Y_SCALE:-1.10}"
export CRADLE_SIDE_RAIL_HEIGHT="${CRADLE_SIDE_RAIL_HEIGHT:-0.12}"
export CRADLE_END_STOP_HEIGHT="${CRADLE_END_STOP_HEIGHT:-0.13}"
export CRADLE_CHEST_PAD_LOCAL_X="${CRADLE_CHEST_PAD_LOCAL_X:--0.02}"
export CRADLE_CHEST_PAD_LOCAL_Y="${CRADLE_CHEST_PAD_LOCAL_Y:-0.0}"
export CRADLE_CHEST_PAD_LOCAL_Z="${CRADLE_CHEST_PAD_LOCAL_Z:-0.10}"
export CRADLE_CHEST_PAD_SIZE_X="${CRADLE_CHEST_PAD_SIZE_X:-0.04}"
export CRADLE_CHEST_PAD_SIZE_Y="${CRADLE_CHEST_PAD_SIZE_Y:-0.38}"
export CRADLE_CHEST_PAD_SIZE_Z="${CRADLE_CHEST_PAD_SIZE_Z:-0.22}"

exec bash "${ROOT_DIR}/scripts/isaac/run_core_world_g1_agile_policy_low_cradle_suite.sh"
