#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run Isaac simulation on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
OUTPUT_DIR="${OUTPUT_DIR:-${ROOT_DIR}/experiments/outputs/direct_carry_task_physical_backend/${STAMP}}"
BACKEND_OUTPUT_DIR="${BACKEND_OUTPUT_DIR:-${OUTPUT_DIR}/backend_anchored_cradle}"
BACKEND_STAMP="${BACKEND_STAMP:-${STAMP}_backend_anchored_cradle}"
BACKEND_LOG="${ROOT_DIR}/logs/core_world_anchored_footstep_carrier/core_world_anchored_footstep_carrier_${BACKEND_STAMP}.log"
SUPPORT_MODE="${SUPPORT_MODE:-replant_world_joint}"
CARRY_POSTURE="${CARRY_POSTURE:-front_mid}"

mkdir -p "${OUTPUT_DIR}" "${BACKEND_OUTPUT_DIR}"
cd "${ROOT_DIR}"

case "${SUPPORT_MODE}" in
  replant_world_joint)
    SUPPORT_ARGS=(--no-fix-anchor-to-world --replant-anchor-world-joint --cumulative-cycle-target)
    DEFAULT_STEP_LENGTH="0.08"
    DEFAULT_CONTROLLER_MODE="physical_anchored_cradle"
    ;;
  fixed_anchor)
    SUPPORT_ARGS=(--fix-anchor-to-world)
    DEFAULT_STEP_LENGTH="${TARGET_X:-0.32}"
    DEFAULT_CONTROLLER_MODE="physical_fixed_anchor_cradle"
    ;;
  dynamic_anchor_feet)
    SUPPORT_ARGS=(--no-fix-anchor-to-world --support-foot-mode fixed_to_anchor --disable-support-reposition)
    DEFAULT_STEP_LENGTH="${TARGET_X:-0.32}"
    DEFAULT_CONTROLLER_MODE="physical_dynamic_anchor_feet_cradle"
    ;;
  legged_anchor_feet)
    SUPPORT_ARGS=(--no-fix-anchor-to-world --support-foot-mode x_prismatic_to_anchor --disable-support-reposition --use-support-foot-drive)
    DEFAULT_STEP_LENGTH="${TARGET_X:-0.16}"
    DEFAULT_CONTROLLER_MODE="physical_legged_anchor_feet_cradle"
    ;;
  alternating_anchor_feet)
    SUPPORT_ARGS=(--no-fix-anchor-to-world --support-foot-mode xz_prismatic_to_anchor --disable-support-reposition --use-support-foot-drive)
    DEFAULT_STEP_LENGTH="${STEP_LENGTH:-0.08}"
    DEFAULT_CONTROLLER_MODE="physical_alternating_anchor_feet_cradle"
    ;;
  alternating_placement_feet)
    SUPPORT_ARGS=(
      --no-fix-anchor-to-world
      --support-foot-mode xz_prismatic_to_anchor
      --support-foot-placement-mode alternating_directional_x
      --disable-support-reposition
      --use-support-foot-drive
    )
    DEFAULT_STEP_LENGTH="${STEP_LENGTH:-0.08}"
    DEFAULT_CONTROLLER_MODE="physical_alternating_placement_feet_cradle"
    ;;
  *)
    echo "Unknown SUPPORT_MODE=${SUPPORT_MODE}; expected replant_world_joint, fixed_anchor, dynamic_anchor_feet, legged_anchor_feet, alternating_anchor_feet, or alternating_placement_feet" >&2
    exit 4
    ;;
esac

case "${CARRY_POSTURE}" in
  front_mid)
    DEFAULT_PAYLOAD_LOCAL_X="0.20"
    DEFAULT_PAYLOAD_LOCAL_Z="0.04"
    DEFAULT_TORSO_Z="0.55"
    ;;
  low_front)
    DEFAULT_PAYLOAD_LOCAL_X="0.24"
    DEFAULT_PAYLOAD_LOCAL_Z="-0.02"
    DEFAULT_TORSO_Z="0.58"
    ;;
  chest_high)
    DEFAULT_PAYLOAD_LOCAL_X="0.16"
    DEFAULT_PAYLOAD_LOCAL_Z="0.12"
    DEFAULT_TORSO_Z="0.55"
    ;;
  front_reach)
    DEFAULT_PAYLOAD_LOCAL_X="0.28"
    DEFAULT_PAYLOAD_LOCAL_Z="0.04"
    DEFAULT_TORSO_Z="0.56"
    ;;
  close_mid)
    DEFAULT_PAYLOAD_LOCAL_X="0.12"
    DEFAULT_PAYLOAD_LOCAL_Z="0.05"
    DEFAULT_TORSO_Z="0.55"
    ;;
  *)
    echo "Unknown CARRY_POSTURE=${CARRY_POSTURE}; expected front_mid, low_front, chest_high, front_reach, or close_mid" >&2
    exit 5
    ;;
esac

CONTROLLER_MODE="${CONTROLLER_MODE:-${DEFAULT_CONTROLLER_MODE}}"
SUPPORT_FOOT_MASS="${SUPPORT_FOOT_MASS:-6.0}"
SUPPORT_FOOT_X_LOWER="${SUPPORT_FOOT_X_LOWER:--0.80}"
SUPPORT_FOOT_X_UPPER="${SUPPORT_FOOT_X_UPPER:-0.20}"
SUPPORT_FOOT_DRIVE_STIFFNESS="${SUPPORT_FOOT_DRIVE_STIFFNESS:-18000.0}"
SUPPORT_FOOT_DRIVE_DAMPING="${SUPPORT_FOOT_DRIVE_DAMPING:-3000.0}"
SUPPORT_FOOT_DRIVE_MAX_FORCE="${SUPPORT_FOOT_DRIVE_MAX_FORCE:-80000.0}"
SUPPORT_FOOT_DRIVE_DIRECTION_SCALE="${SUPPORT_FOOT_DRIVE_DIRECTION_SCALE:--1.0}"
SUPPORT_FOOT_PLACEMENT_MODE="${SUPPORT_FOOT_PLACEMENT_MODE:-alternating_fixed_x}"
SUPPORT_FOOT_Z_LOWER="${SUPPORT_FOOT_Z_LOWER:--0.005}"
SUPPORT_FOOT_Z_UPPER="${SUPPORT_FOOT_Z_UPPER:-0.120}"
SUPPORT_FOOT_Z_DRIVE_STIFFNESS="${SUPPORT_FOOT_Z_DRIVE_STIFFNESS:-14000.0}"
SUPPORT_FOOT_Z_DRIVE_DAMPING="${SUPPORT_FOOT_Z_DRIVE_DAMPING:-1800.0}"
SUPPORT_FOOT_Z_DRIVE_MAX_FORCE="${SUPPORT_FOOT_Z_DRIVE_MAX_FORCE:-70000.0}"
SUPPORT_FOOT_STEP_HEIGHT="${SUPPORT_FOOT_STEP_HEIGHT:-0.070}"
SUPPORT_FOOT_STANCE_X="${SUPPORT_FOOT_STANCE_X:--0.080}"
SUPPORT_FOOT_SWING_X="${SUPPORT_FOOT_SWING_X:-0.080}"
SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION="${SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION:-0.0}"
ENABLE_SUPPORT_FOOT_CONTACT_REPORT="${ENABLE_SUPPORT_FOOT_CONTACT_REPORT:-0}"
SUPPORT_FOOT_CONTACT_REPORT_THRESHOLD="${SUPPORT_FOOT_CONTACT_REPORT_THRESHOLD:-0.0}"
SUPPORT_FOOT_EFFORT_CONTACT_THRESHOLD="${SUPPORT_FOOT_EFFORT_CONTACT_THRESHOLD:-1.0}"
SUPPORT_FOOT_CONTINUITY_GRACE_STEPS="${SUPPORT_FOOT_CONTINUITY_GRACE_STEPS:-0}"
STANCE_FOOT_WORLD_LOCK="${STANCE_FOOT_WORLD_LOCK:-0}"
FREEZE_LOCKED_STANCE_FOOT_TARGETS="${FREEZE_LOCKED_STANCE_FOOT_TARGETS:-0}"
FREEZE_COMMANDED_STANCE_FOOT_TARGETS="${FREEZE_COMMANDED_STANCE_FOOT_TARGETS:-0}"
PLANTED_STANCE_RAIL_PROPULSION="${PLANTED_STANCE_RAIL_PROPULSION:-0}"
FEEDBACK_STEP_CONTROLLER="${FEEDBACK_STEP_CONTROLLER:-0}"
FEEDBACK_STEP_X_GAIN="${FEEDBACK_STEP_X_GAIN:-0.0}"
FEEDBACK_STEP_X_LIMIT="${FEEDBACK_STEP_X_LIMIT:-0.030}"
FEEDBACK_STEP_TILT_GAIN="${FEEDBACK_STEP_TILT_GAIN:-0.0}"
FEEDBACK_STEP_TILT_LIMIT="${FEEDBACK_STEP_TILT_LIMIT:-0.020}"
ENABLE_ONLINE_PROBE_ADAPTIVE_SUPPORT="${ENABLE_ONLINE_PROBE_ADAPTIVE_SUPPORT:-0}"
ONLINE_PROBE_ADAPTIVE_MEDIUM_THRESHOLD="${ONLINE_PROBE_ADAPTIVE_MEDIUM_THRESHOLD:-0.58}"
ONLINE_PROBE_ADAPTIVE_HIGH_THRESHOLD="${ONLINE_PROBE_ADAPTIVE_HIGH_THRESHOLD:-0.75}"
ONLINE_LOW_SUPPORT_STEP_HEIGHT="${ONLINE_LOW_SUPPORT_STEP_HEIGHT:-0.120}"
ONLINE_LOW_SUPPORT_DOUBLE_SUPPORT_FRACTION="${ONLINE_LOW_SUPPORT_DOUBLE_SUPPORT_FRACTION:-0.12}"
if [[ -z "${ONLINE_LOW_SUPPORT_STANCE_X:-}" ]]; then ONLINE_LOW_SUPPORT_STANCE_X="-0.130"; fi
ONLINE_LOW_SUPPORT_SWING_X="${ONLINE_LOW_SUPPORT_SWING_X:-0.130}"
ONLINE_MEDIUM_SUPPORT_STEP_HEIGHT="${ONLINE_MEDIUM_SUPPORT_STEP_HEIGHT:-0.100}"
ONLINE_MEDIUM_SUPPORT_DOUBLE_SUPPORT_FRACTION="${ONLINE_MEDIUM_SUPPORT_DOUBLE_SUPPORT_FRACTION:-0.18}"
if [[ -z "${ONLINE_MEDIUM_SUPPORT_STANCE_X:-}" ]]; then ONLINE_MEDIUM_SUPPORT_STANCE_X="-0.115"; fi
ONLINE_MEDIUM_SUPPORT_SWING_X="${ONLINE_MEDIUM_SUPPORT_SWING_X:-0.115}"
ONLINE_HIGH_SUPPORT_STEP_HEIGHT="${ONLINE_HIGH_SUPPORT_STEP_HEIGHT:-0.080}"
ONLINE_HIGH_SUPPORT_DOUBLE_SUPPORT_FRACTION="${ONLINE_HIGH_SUPPORT_DOUBLE_SUPPORT_FRACTION:-0.24}"
if [[ -z "${ONLINE_HIGH_SUPPORT_STANCE_X:-}" ]]; then ONLINE_HIGH_SUPPORT_STANCE_X="-0.100"; fi
ONLINE_HIGH_SUPPORT_SWING_X="${ONLINE_HIGH_SUPPORT_SWING_X:-0.100}"
ENABLE_ONLINE_PROBE_ADAPTIVE_HOLD="${ENABLE_ONLINE_PROBE_ADAPTIVE_HOLD:-0}"
ONLINE_LOW_HOLD_CLOSURE_FRACTION="${ONLINE_LOW_HOLD_CLOSURE_FRACTION:-0.45}"
ONLINE_MEDIUM_HOLD_CLOSURE_FRACTION="${ONLINE_MEDIUM_HOLD_CLOSURE_FRACTION:-0.75}"
ONLINE_HIGH_HOLD_CLOSURE_FRACTION="${ONLINE_HIGH_HOLD_CLOSURE_FRACTION:-1.0}"
export SUPPORT_FOOT_MASS
export SUPPORT_FOOT_X_LOWER
export SUPPORT_FOOT_X_UPPER
export SUPPORT_FOOT_DRIVE_STIFFNESS
export SUPPORT_FOOT_DRIVE_DAMPING
export SUPPORT_FOOT_DRIVE_MAX_FORCE
export SUPPORT_FOOT_DRIVE_DIRECTION_SCALE
export SUPPORT_FOOT_PLACEMENT_MODE
export SUPPORT_FOOT_Z_LOWER
export SUPPORT_FOOT_Z_UPPER
export SUPPORT_FOOT_Z_DRIVE_STIFFNESS
export SUPPORT_FOOT_Z_DRIVE_DAMPING
export SUPPORT_FOOT_Z_DRIVE_MAX_FORCE
export SUPPORT_FOOT_STEP_HEIGHT
export SUPPORT_FOOT_STANCE_X
export SUPPORT_FOOT_SWING_X
export SUPPORT_FOOT_DOUBLE_SUPPORT_FRACTION
export ENABLE_SUPPORT_FOOT_CONTACT_REPORT
export SUPPORT_FOOT_CONTACT_REPORT_THRESHOLD
export SUPPORT_FOOT_EFFORT_CONTACT_THRESHOLD
export SUPPORT_FOOT_CONTINUITY_GRACE_STEPS
export STANCE_FOOT_WORLD_LOCK
export FREEZE_LOCKED_STANCE_FOOT_TARGETS
export FREEZE_COMMANDED_STANCE_FOOT_TARGETS
export PLANTED_STANCE_RAIL_PROPULSION
export FEEDBACK_STEP_CONTROLLER
export FEEDBACK_STEP_X_GAIN
export FEEDBACK_STEP_X_LIMIT
export FEEDBACK_STEP_TILT_GAIN
export FEEDBACK_STEP_TILT_LIMIT
export ENABLE_ONLINE_PROBE_ADAPTIVE_SUPPORT
export ONLINE_PROBE_ADAPTIVE_MEDIUM_THRESHOLD
export ONLINE_PROBE_ADAPTIVE_HIGH_THRESHOLD
export ONLINE_LOW_SUPPORT_STEP_HEIGHT
export ONLINE_LOW_SUPPORT_DOUBLE_SUPPORT_FRACTION
export ONLINE_LOW_SUPPORT_STANCE_X
export ONLINE_LOW_SUPPORT_SWING_X
export ONLINE_MEDIUM_SUPPORT_STEP_HEIGHT
export ONLINE_MEDIUM_SUPPORT_DOUBLE_SUPPORT_FRACTION
export ONLINE_MEDIUM_SUPPORT_STANCE_X
export ONLINE_MEDIUM_SUPPORT_SWING_X
export ONLINE_HIGH_SUPPORT_STEP_HEIGHT
export ONLINE_HIGH_SUPPORT_DOUBLE_SUPPORT_FRACTION
export ONLINE_HIGH_SUPPORT_STANCE_X
export ONLINE_HIGH_SUPPORT_SWING_X
export ENABLE_ONLINE_PROBE_ADAPTIVE_HOLD
export ONLINE_LOW_HOLD_CLOSURE_FRACTION
export ONLINE_MEDIUM_HOLD_CLOSURE_FRACTION
export ONLINE_HIGH_HOLD_CLOSURE_FRACTION

echo "[CONFIG] STAMP=${STAMP} CONTROLLER_MODE=${CONTROLLER_MODE} BACKEND=anchored_cradle SUPPORT_MODE=${SUPPORT_MODE} CARRY_POSTURE=${CARRY_POSTURE} TARGET_X=${TARGET_X:-0.32} PAYLOAD_MASS=${PAYLOAD_MASS:-8.0}"

CORE_ENV=(
  "STAMP=${BACKEND_STAMP}"
  "OUTPUT_DIR=${BACKEND_OUTPUT_DIR}"
  "STEPS=${STEPS:-980}"
  "TARGET_X=${TARGET_X:-0.32}"
  "STEP_LENGTH=${STEP_LENGTH:-${DEFAULT_STEP_LENGTH}}"
  "STANCE_STEPS=${STANCE_STEPS:-120}"
  "SETTLE_STEPS=${SETTLE_STEPS:-60}"
  "PROBE_STEPS=${PROBE_STEPS:-0}"
  "PROBE_MODE=${PROBE_MODE:-horizontal_push_pull}"
  "PROBE_X_AMPLITUDE=${PROBE_X_AMPLITUDE:-0.0}"
  "PROBE_Z_AMPLITUDE=${PROBE_Z_AMPLITUDE:-0.0}"
  "BELIEF_COMPLIANCE_LOW_THRESHOLD=${BELIEF_COMPLIANCE_LOW_THRESHOLD:-0.08}"
  "BELIEF_COMPLIANCE_HIGH_THRESHOLD=${BELIEF_COMPLIANCE_HIGH_THRESHOLD:-0.22}"
  "PAYLOAD_MODE=${PAYLOAD_MODE:-cradle_free_box}"
  "PAYLOAD_MASS=${PAYLOAD_MASS:-8.0}"
  "BOX_SEED=${BOX_SEED:-0}"
  "RANDOMIZE_PAYLOAD=${RANDOMIZE_PAYLOAD:-0}"
  "PAYLOAD_MASS_MIN=${PAYLOAD_MASS_MIN:-4.0}"
  "PAYLOAD_MASS_MAX=${PAYLOAD_MASS_MAX:-12.0}"
  "PAYLOAD_SIZE_JITTER=${PAYLOAD_SIZE_JITTER:-0.0}"
  "PAYLOAD_COM_OFFSET_RANGE_X=${PAYLOAD_COM_OFFSET_RANGE_X:-0.0}"
  "PAYLOAD_COM_OFFSET_RANGE_Y=${PAYLOAD_COM_OFFSET_RANGE_Y:-0.0}"
  "PAYLOAD_COM_OFFSET_RANGE_Z=${PAYLOAD_COM_OFFSET_RANGE_Z:-0.0}"
  "TORSO_MASS=${TORSO_MASS:-36.0}"
  "TORSO_Z=${TORSO_Z:-${DEFAULT_TORSO_Z}}"
  "PAYLOAD_LOCAL_X=${PAYLOAD_LOCAL_X:-${DEFAULT_PAYLOAD_LOCAL_X}}"
  "PAYLOAD_LOCAL_Z=${PAYLOAD_LOCAL_Z:-${DEFAULT_PAYLOAD_LOCAL_Z}}"
  "DRIVE_STIFFNESS=${DRIVE_STIFFNESS:-22000.0}"
  "DRIVE_DAMPING=${DRIVE_DAMPING:-3500.0}"
  "DRIVE_MAX_FORCE=${DRIVE_MAX_FORCE:-60000.0}"
  "RAIL_JOINT_COUNT=${RAIL_JOINT_COUNT:-4}"
  "RAIL_LOWER=${RAIL_LOWER:--0.04}"
  "RAIL_UPPER=${RAIL_UPPER:-0.10}"
  "STOP_THRESHOLD=${STOP_THRESHOLD:-0.002}"
  "STATIC_FRICTION=${STATIC_FRICTION:-3.0}"
  "DYNAMIC_FRICTION=${DYNAMIC_FRICTION:-2.5}"
  "ENABLE_SUPPORT_FOOT_CONTACT_REPORT=${ENABLE_SUPPORT_FOOT_CONTACT_REPORT:-0}"
  "SUPPORT_FOOT_CONTACT_REPORT_THRESHOLD=${SUPPORT_FOOT_CONTACT_REPORT_THRESHOLD:-0.0}"
  "SUPPORT_FOOT_EFFORT_CONTACT_THRESHOLD=${SUPPORT_FOOT_EFFORT_CONTACT_THRESHOLD:-1.0}"
  "SUPPORT_FOOT_CONTINUITY_GRACE_STEPS=${SUPPORT_FOOT_CONTINUITY_GRACE_STEPS:-0}"
  "STANCE_FOOT_WORLD_LOCK=${STANCE_FOOT_WORLD_LOCK:-0}"
  "FREEZE_LOCKED_STANCE_FOOT_TARGETS=${FREEZE_LOCKED_STANCE_FOOT_TARGETS:-0}"
  "FREEZE_COMMANDED_STANCE_FOOT_TARGETS=${FREEZE_COMMANDED_STANCE_FOOT_TARGETS:-0}"
  "PLANTED_STANCE_RAIL_PROPULSION=${PLANTED_STANCE_RAIL_PROPULSION:-0}"
  "ENABLE_ONLINE_PROBE_ADAPTIVE_SUPPORT=${ENABLE_ONLINE_PROBE_ADAPTIVE_SUPPORT}"
  "ONLINE_PROBE_ADAPTIVE_MEDIUM_THRESHOLD=${ONLINE_PROBE_ADAPTIVE_MEDIUM_THRESHOLD}"
  "ONLINE_PROBE_ADAPTIVE_HIGH_THRESHOLD=${ONLINE_PROBE_ADAPTIVE_HIGH_THRESHOLD}"
  "ONLINE_LOW_SUPPORT_STEP_HEIGHT=${ONLINE_LOW_SUPPORT_STEP_HEIGHT}"
  "ONLINE_LOW_SUPPORT_DOUBLE_SUPPORT_FRACTION=${ONLINE_LOW_SUPPORT_DOUBLE_SUPPORT_FRACTION}"
  "ONLINE_LOW_SUPPORT_STANCE_X=${ONLINE_LOW_SUPPORT_STANCE_X}"
  "ONLINE_LOW_SUPPORT_SWING_X=${ONLINE_LOW_SUPPORT_SWING_X}"
  "ONLINE_MEDIUM_SUPPORT_STEP_HEIGHT=${ONLINE_MEDIUM_SUPPORT_STEP_HEIGHT}"
  "ONLINE_MEDIUM_SUPPORT_DOUBLE_SUPPORT_FRACTION=${ONLINE_MEDIUM_SUPPORT_DOUBLE_SUPPORT_FRACTION}"
  "ONLINE_MEDIUM_SUPPORT_STANCE_X=${ONLINE_MEDIUM_SUPPORT_STANCE_X}"
  "ONLINE_MEDIUM_SUPPORT_SWING_X=${ONLINE_MEDIUM_SUPPORT_SWING_X}"
  "ONLINE_HIGH_SUPPORT_STEP_HEIGHT=${ONLINE_HIGH_SUPPORT_STEP_HEIGHT}"
  "ONLINE_HIGH_SUPPORT_DOUBLE_SUPPORT_FRACTION=${ONLINE_HIGH_SUPPORT_DOUBLE_SUPPORT_FRACTION}"
  "ONLINE_HIGH_SUPPORT_STANCE_X=${ONLINE_HIGH_SUPPORT_STANCE_X}"
  "ONLINE_HIGH_SUPPORT_SWING_X=${ONLINE_HIGH_SUPPORT_SWING_X}"
  "ENABLE_ONLINE_PROBE_ADAPTIVE_HOLD=${ENABLE_ONLINE_PROBE_ADAPTIVE_HOLD}"
  "ONLINE_LOW_HOLD_CLOSURE_FRACTION=${ONLINE_LOW_HOLD_CLOSURE_FRACTION}"
  "ONLINE_MEDIUM_HOLD_CLOSURE_FRACTION=${ONLINE_MEDIUM_HOLD_CLOSURE_FRACTION}"
  "ONLINE_HIGH_HOLD_CLOSURE_FRACTION=${ONLINE_HIGH_HOLD_CLOSURE_FRACTION}"
  "SUPPORT_FOOT_PLACEMENT_MODE=${SUPPORT_FOOT_PLACEMENT_MODE}"
  "DEBUG_CORE_CMD=${DEBUG_CORE_CMD:-0}"
  "DEVICE=${DEVICE:-cpu}"
)
env "${CORE_ENV[@]}" bash scripts/isaac/run_core_world_anchored_footstep_carrier.sh \
  "${SUPPORT_ARGS[@]}" \
  "$@"

python3 scripts/isaac/normalize_direct_carry_backend_summary.py \
  --backend-summary "${BACKEND_OUTPUT_DIR}/core_world_anchored_footstep_carrier_summary.json" \
  --backend-log "${BACKEND_LOG}" \
  --controller-mode "${CONTROLLER_MODE}" \
  --carry-posture "${CARRY_POSTURE}" \
  --output-summary "${OUTPUT_DIR}/direct_carry_task_physical_backend_summary.json"

echo "[INFO] Output: ${OUTPUT_DIR}"
