#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run G1 low-carry showcase on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
RECORD_STAMP="${RECORD_STAMP:-20260707_g1_lowcarry_060_runtime_chestpad_showcase_record_min700}"
VIS_STAMP="${VIS_STAMP:-20260707_g1_lowcarry_060_runtime_chestpad_showcase_render_min700}"
RECORD_DIR="${ROOT_DIR}/experiments/outputs/core_world_g1_agile_policy_low_cradle/${RECORD_STAMP}/agile_low_cradle_freebox_walk"
RENDER_DIR="${ROOT_DIR}/experiments/visuals/g1_replay_showcase/${VIS_STAMP}"

cd "${ROOT_DIR}"

env \
  SUITE_STAMP="${RECORD_STAMP}" \
  LARGERBOX_STRICT_MODE=lowcarry \
  FREE_BOX_MASS=0.60 \
  FREE_STEPS=819 \
  FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL=2.35 \
  FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL=2.35 \
  TARGET_WINDOW_CENTER=2.0 \
  TARGET_WINDOW_HALFWIDTH=0.35 \
  MIN_TARGET_WINDOW_BOTH_STABLE_STEPS=80 \
  MIN_TARGET_WINDOW_BOTH_LONGEST_STREAK_STEPS=50 \
  MIN_TARGET_WINDOW_BOTH_STREAK_AT_END_STEPS=40 \
  MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STABLE_STEPS=80 \
  MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_LONGEST_STREAK_STEPS=50 \
  MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STREAK_AT_END_STEPS=40 \
  MIN_AGILE_COMMAND_HOLD_FINAL_ACTIVE_STEPS=399 \
  MAX_FINAL_HOLD_COMMAND_X=0.001 \
  MAX_FINAL_HOLD_COMMAND_Y=0.003 \
  MAX_FINAL_HOLD_COMMAND_YAW=0.001 \
  MIN_FINAL_HOLD_ROBOT_Z=0.45 \
  MIN_FINAL_HOLD_BOX_Z=0.45 \
  MAX_FINAL_HOLD_TILT=0.35 \
  MAX_FINAL_HOLD_BOX_TILT=0.45 \
  MAX_FINAL_HOLD_FALL_EVENTS=0 \
  MAX_FINAL_HOLD_BOX_DROP_EVENTS=0 \
  AGILE_COMMAND_HOLD_YAW_CORRECTION=1 \
  AGILE_COMMAND_HOLD_YAW_GAIN=0.0 \
  AGILE_COMMAND_HOLD_YAW_LIMIT=0.0 \
  AGILE_COMMAND_HOLD_YAW_SIGN=-1.0 \
  AGILE_COMMAND_HOLD_LATERAL_CORRECTION=1 \
  AGILE_COMMAND_HOLD_LATERAL_TERMINAL_ONLY=1 \
  AGILE_COMMAND_HOLD_LATERAL_ERROR_START=0.45 \
  AGILE_COMMAND_HOLD_LATERAL_USE_EXCESS_ERROR=1 \
  AGILE_COMMAND_HOLD_LATERAL_GAIN=0.006 \
  AGILE_COMMAND_HOLD_LATERAL_LIMIT=0.0015 \
  AGILE_COMMAND_HOLD_LATERAL_SIGN=1.0 \
  AGILE_COMMAND_HOLD_LATERAL_MAX_TILT=0.30 \
  AGILE_COMMAND_HOLD_LATERAL_MAX_BOX_TILT=0.35 \
  AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL=0.65 \
  AGILE_COMMAND_HOLD_TERMINAL_SCALE=0.015 \
  AGILE_COMMAND_HOLD_TERMINAL_LATCH=1 \
  AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL=0.6 \
  AGILE_COMMAND_HOLD_FINAL_SCALE=0.0 \
  AGILE_COMMAND_HOLD_FINAL_LATCH=1 \
  CRADLE_TOP_LID_LOCAL_Z=0.13 \
  CRADLE_TOP_LID_THICKNESS=0.014 \
  CRADLE_CHEST_PAD_ENABLED=1 \
  CRADLE_CHEST_PAD_SPAWN_ON_TRIGGER=1 \
  CRADLE_CHEST_PAD_ENABLE_ON_TARGET_WINDOW=1 \
  CRADLE_CHEST_PAD_TARGET_WINDOW_MIN_STEP=700 \
  CRADLE_CHEST_PAD_LOCAL_X=-0.02 \
  CRADLE_CHEST_PAD_LOCAL_Z=0.10 \
  CRADLE_CHEST_PAD_SIZE_X=0.04 \
  CRADLE_CHEST_PAD_SIZE_Y=0.38 \
  CRADLE_CHEST_PAD_SIZE_Z=0.22 \
  RECORD_REPLAY_CSV=1 \
  RECORD_REPLAY_EVERY_N_STEPS="${RECORD_REPLAY_EVERY_N_STEPS:-4}" \
  COMPUTE_SIDE_STARTUP_SLEEP="${COMPUTE_SIDE_STARTUP_SLEEP:-5}" \
  bash scripts/isaac/run_core_world_g1_largerbox_strict_suite.sh

REPLAY_CSV="${RECORD_DIR}/core_world_g1_box_scene_replay.csv" \
OUTPUT_DIR="${RENDER_DIR}" \
CAPTURE_EVERY_N_ROWS="${CAPTURE_EVERY_N_ROWS:-1}" \
MAX_FRAMES="${MAX_FRAMES:-160}" \
WIDTH="${WIDTH:-1280}" \
HEIGHT="${HEIGHT:-720}" \
MIN_REPLAY_ROWS="${MIN_REPLAY_ROWS:-100}" \
MIN_RENDER_FRAMES="${MIN_RENDER_FRAMES:-80}" \
  bash scripts/isaac/run_core_world_g1_replay_showcase_render.sh

echo "record_dir=${RECORD_DIR}"
echo "render_dir=${RENDER_DIR}"
echo "replay_csv=${RECORD_DIR}/core_world_g1_box_scene_replay.csv"
echo "annotated_mp4=${RENDER_DIR}/g1_replay_showcase_annotated.mp4"
