#!/usr/bin/env bash
set -euo pipefail

if [[ "$(hostname)" == mgmtserver* ]]; then
  echo "Refusing to run G1 larger-box final-hold posture matrix on login/management node: $(hostname)" >&2
  exit 2
fi

ROOT_DIR="${ROOT_DIR:-/public/home/yanhongru/Curiosity}"
export MATRIX_STAMP="${MATRIX_STAMP:-20260706_g1_largerbox_finalhold_targetwindow_posture_matrix}"
export LARGERBOX_POSTURE_MODES="${LARGERBOX_POSTURE_MODES:-boxtilt lowcarry chestpad}"

export FREE_STEPS="${FREE_STEPS:-900}"
export TARGET_X="${TARGET_X:--1.2}"
export TARGET_Y="${TARGET_Y:-0.0}"

export FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL="${FREE_MAX_FINAL_ROBOT_TARGET_DIRECTED_TRAVEL:-2.35}"
export FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL="${FREE_MAX_FINAL_BOX_TARGET_DIRECTED_TRAVEL:-2.35}"

export TARGET_WINDOW_CENTER="${TARGET_WINDOW_CENTER:-2.0}"
export TARGET_WINDOW_HALFWIDTH="${TARGET_WINDOW_HALFWIDTH:-0.35}"
export MIN_TARGET_WINDOW_BOTH_STABLE_STEPS="${MIN_TARGET_WINDOW_BOTH_STABLE_STEPS:-80}"
export MIN_TARGET_WINDOW_BOTH_LONGEST_STREAK_STEPS="${MIN_TARGET_WINDOW_BOTH_LONGEST_STREAK_STEPS:-50}"
export MIN_TARGET_WINDOW_BOTH_STREAK_AT_END_STEPS="${MIN_TARGET_WINDOW_BOTH_STREAK_AT_END_STEPS:-40}"
export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STABLE_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STABLE_STEPS:-80}"
export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_LONGEST_STREAK_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_LONGEST_STREAK_STEPS:-50}"
export MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STREAK_AT_END_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_HOLD_STREAK_AT_END_STEPS:-40}"
export MIN_TARGET_WINDOW_BOTH_FINAL_STAND_STABLE_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_STAND_STABLE_STEPS:-60}"
export MIN_TARGET_WINDOW_BOTH_FINAL_STAND_LONGEST_STREAK_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_STAND_LONGEST_STREAK_STEPS:-40}"
export MIN_TARGET_WINDOW_BOTH_FINAL_STAND_STREAK_AT_END_STEPS="${MIN_TARGET_WINDOW_BOTH_FINAL_STAND_STREAK_AT_END_STEPS:-30}"

export MIN_AGILE_COMMAND_HOLD_FINAL_ACTIVE_STEPS="${MIN_AGILE_COMMAND_HOLD_FINAL_ACTIVE_STEPS:-120}"
export MIN_AGILE_COMMAND_HOLD_FINAL_STAND_ACTIVE_STEPS="${MIN_AGILE_COMMAND_HOLD_FINAL_STAND_ACTIVE_STEPS:-80}"
export MAX_FINAL_HOLD_COMMAND_X="${MAX_FINAL_HOLD_COMMAND_X:-0.001}"
export MAX_FINAL_HOLD_COMMAND_Y="${MAX_FINAL_HOLD_COMMAND_Y:-0.001}"
export MAX_FINAL_HOLD_COMMAND_YAW="${MAX_FINAL_HOLD_COMMAND_YAW:-0.001}"
export MIN_FINAL_HOLD_ROBOT_Z="${MIN_FINAL_HOLD_ROBOT_Z:-0.45}"
export MIN_FINAL_HOLD_BOX_Z="${MIN_FINAL_HOLD_BOX_Z:-0.45}"
export MAX_FINAL_HOLD_TILT="${MAX_FINAL_HOLD_TILT:-0.35}"
export MAX_FINAL_HOLD_BOX_TILT="${MAX_FINAL_HOLD_BOX_TILT:-0.45}"
export MAX_FINAL_HOLD_FALL_EVENTS="${MAX_FINAL_HOLD_FALL_EVENTS:-0}"
export MAX_FINAL_HOLD_BOX_DROP_EVENTS="${MAX_FINAL_HOLD_BOX_DROP_EVENTS:-0}"
export MIN_FINAL_STAND_ROBOT_Z="${MIN_FINAL_STAND_ROBOT_Z:-0.45}"
export MIN_FINAL_STAND_BOX_Z="${MIN_FINAL_STAND_BOX_Z:-0.45}"
export MAX_FINAL_STAND_TILT="${MAX_FINAL_STAND_TILT:-0.35}"
export MAX_FINAL_STAND_BOX_TILT="${MAX_FINAL_STAND_BOX_TILT:-0.45}"
export MAX_FINAL_STAND_FALL_EVENTS="${MAX_FINAL_STAND_FALL_EVENTS:-0}"
export MAX_FINAL_STAND_BOX_DROP_EVENTS="${MAX_FINAL_STAND_BOX_DROP_EVENTS:-0}"

export AGILE_COMMAND_HOLD_YAW_CORRECTION="${AGILE_COMMAND_HOLD_YAW_CORRECTION:-1}"
export AGILE_COMMAND_HOLD_YAW_GAIN="${AGILE_COMMAND_HOLD_YAW_GAIN:-0.04}"
export AGILE_COMMAND_HOLD_YAW_LIMIT="${AGILE_COMMAND_HOLD_YAW_LIMIT:-0.08}"
export AGILE_COMMAND_HOLD_YAW_SIGN="${AGILE_COMMAND_HOLD_YAW_SIGN:--1.0}"
export AGILE_COMMAND_HOLD_LATERAL_CORRECTION="${AGILE_COMMAND_HOLD_LATERAL_CORRECTION:-0}"
export AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL="${AGILE_COMMAND_HOLD_TERMINAL_BOX_TARGET_TRAVEL:-0.65}"
export AGILE_COMMAND_HOLD_TERMINAL_SCALE="${AGILE_COMMAND_HOLD_TERMINAL_SCALE:-0.015}"
export AGILE_COMMAND_HOLD_TERMINAL_LATCH="${AGILE_COMMAND_HOLD_TERMINAL_LATCH:-1}"
export AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL="${AGILE_COMMAND_HOLD_FINAL_BOX_TARGET_TRAVEL:-2.0}"
export AGILE_COMMAND_HOLD_FINAL_SCALE="${AGILE_COMMAND_HOLD_FINAL_SCALE:-0.0}"
export AGILE_COMMAND_HOLD_FINAL_LATCH="${AGILE_COMMAND_HOLD_FINAL_LATCH:-1}"
export AGILE_COMMAND_HOLD_FINAL_STAND="${AGILE_COMMAND_HOLD_FINAL_STAND:-1}"
export AGILE_COMMAND_HOLD_FINAL_STAND_DELAY_STEPS="${AGILE_COMMAND_HOLD_FINAL_STAND_DELAY_STEPS:-20}"
export AGILE_COMMAND_HOLD_STAND_BLEND_RATE="${AGILE_COMMAND_HOLD_STAND_BLEND_RATE:-0.02}"

exec bash "${ROOT_DIR}/scripts/isaac/run_core_world_g1_largerbox_posture_matrix.sh"
