# SPDX-License-Identifier: BSD-3-Clause
"""Train SUGAR's Refiner in Newton -- stage 1 of the pipeline, with plain PPO.

Why this exists. The Refiner is the teacher BCPPO distils, and SUGAR never released it:
``demo_ckpts/CarryBox`` ships only ``tracker.pt`` and ``generator.ckpt``. The only Refiner
on this filesystem, ``refiner_model10000.pt``, drives Newton off the reference by frame 14
and never lifts the box, against the released tracker's frame 67 and 0.46 m. Training our
own here removes two blockers at once:

* **The teacher.** Whatever is wrong with loading their weights against our 890-D vector
  stops mattering, because a policy trained here learns whatever this observation encodes.
  A permuted or differently-framed term is only fatal when importing *someone else's*
  weights; train from scratch and the representation is self-consistent by construction.
* **The reference motion.** ``train.sh:40`` points the tracker stage at
  ``rollout_datasets/refiner/rl_dataset`` -- a *recording of what the Refiner achieved* --
  not at ``data/CarryBox``. That dataset does not exist here and cannot be downloaded; it
  is generated by rolling out a trained Refiner. And rolling ours out in Newton gives a
  reference that is feasible under Newton's contact model, which an IsaacLab-generated one
  would not be.

What is SUGAR's and what is ours. The algorithm is ``BasePPORunnerCfg``
(``agents/rsl_rl_ppo_cfg.py``) reproduced field for field below -- it differs from
``BCPPORunnerCfg`` only by ``init_noise_std`` 1.0 against 0.5, which is why this file is
thin. The environment is the one ``carrybox_env`` already implements: the refiner and
tracker configs share all 15 reward terms at identical weights and all 6 termination terms
at identical thresholds (verified against ``base_refiner_env_cfg.py`` and
``base_tracker_env_cfg.py``). The single difference that matters is the observation --
``base_refiner_env_cfg.py:254`` sets ``policy = critic = PrivilegedCfg``, so the actor
reads the same 890-D vector as the critic and there is no teacher group.

    python -m sugar_newton.rl.train_refiner --num-envs 512 --max-iterations 30001

Known deviations, recorded rather than hidden:

* ``init_with_ref=False`` in the refiner config against the tracker's ``True``; we always
  initialise from the reference, as the tracker stage does.
* No start-state pool (``start_init_env_ratio=0.25``, ``pool_warmup_steps=1000*24``); we
  sample a uniform random start frame.
* No ``Unoise`` observation corruption. The refiner's ``PrivilegedCfg`` declares no
  ``enable_corruption``, unlike the tracker's group, so this one may already be faithful.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import torch
import warp as wp

from sugar_newton.rl.run_dir import bind_wandb_run
from sugar_newton.rl.train_bcppo import attach_video, ensure_wandb_credentials


def runner_cfg(args) -> dict:
    """SUGAR's ``BasePPORunnerCfg``, with only the run-length fields taken from ``args``.

    ``obs_groups`` has no ``teacher`` entry: rsl_rl builds the actor from the ``policy``
    group, and for this stage that group *is* the privileged vector.
    """
    return {
        "num_steps_per_env": 24,
        "max_iterations": args.max_iterations,
        "save_interval": args.save_interval,
        "experiment_name": args.run_name,
        "empirical_normalization": False,
        "obs_groups": {"policy": ["policy"], "critic": ["critic"]},
        "policy": {
            "class_name": "ActorCritic",
            # 1.0 here, against BCPPO's 0.5. The refiner explores from scratch; the tracker
            # starts by imitating a teacher and wants a tighter initial distribution.
            "init_noise_std": 1.0,
            "actor_hidden_dims": [512, 256, 128],
            "critic_hidden_dims": [512, 256, 128],
            "activation": "elu",
        },
        "algorithm": {
            "class_name": "PPO",
            "value_loss_coef": 1.0,
            "use_clipped_value_loss": True,
            "clip_param": 0.2,
            "entropy_coef": 0.005,
            "num_learning_epochs": 5,
            "num_mini_batches": 4,
            "learning_rate": 1.0e-3,
            "schedule": "adaptive",
            "gamma": 0.99,
            "lam": 0.95,
            "desired_kl": 0.01,
            "max_grad_norm": 1.0,
        },
        "logger": args.logger,
        "wandb_project": args.wandb_project,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--num-envs", type=int, default=512)
    ap.add_argument("--max-iterations", type=int, default=30001,
                    help="ABSOLUTE target iteration (SUGAR's BasePPORunnerCfg value), not "
                         "a per-leg count: a resumed run trains only the remainder")
    ap.add_argument("--save-interval", type=int, default=25,
                    help="iterations between checkpoints; must be well inside what one "
                         "allocation reaches or a wall-clock kill loses the leg")
    ap.add_argument("--clips", nargs="*", default=None)
    ap.add_argument("--episode-length", type=int, default=300)
    ap.add_argument("--substeps", type=int, default=4)
    ap.add_argument("--mu", type=float, default=1.0)
    ap.add_argument("--resume", default="", help="checkpoint to resume from")
    ap.add_argument("--run-name", default="carrybox_refiner")
    ap.add_argument("--log-root", default="logs/newton_refiner")
    ap.add_argument("--logger", default="wandb", choices=("wandb", "tensorboard"))
    ap.add_argument("--wandb-project", default="sugar_newton")
    ap.add_argument("--eval-minutes", type=float, default=20.0,
                    help="wall-clock minutes between evaluation videos; 0 disables")
    ap.add_argument("--video-interval", type=int, default=0,
                    help="also evaluate every N iterations; 0 disables")
    ap.add_argument("--video-frames", type=int, default=400)
    ap.add_argument("--no-tactile-video", action="store_true")
    ap.add_argument("--canvas-tris", type=int, default=3000)
    ap.add_argument("--box-tris", type=int, default=2000,
                    help="decimated box collider triangles; 0 keeps the asset's ~100k")
    ap.add_argument("--hand-tris", type=int, default=0)
    ap.add_argument("--margin", type=float, default=0.0)
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    # Consumed by attach_video and by make(); this flag is the whole difference between
    # this stage and the tracker stage.
    args.privileged_policy = True

    if args.logger == "wandb":
        ensure_wandb_credentials()

    from rsl_rl.runners import OnPolicyRunner

    from sugar_newton.rl.vec_env import OBS_DIMS, make

    world_size = int(os.environ.get("WORLD_SIZE", "1"))
    local_rank = int(os.environ.get("LOCAL_RANK", "0"))
    rank = int(os.environ.get("RANK", "0"))
    if world_size > 1:
        args.device = f"cuda:{local_rank}"
        torch.cuda.set_device(local_rank)

    wp.init()
    torch.manual_seed(args.seed + rank)

    env = make(args.num_envs, privileged_policy=True, clip_names=args.clips,
               episode_length=args.episode_length, substeps=args.substeps, mu=args.mu,
               device=args.device, seed=args.seed + rank, box_tris=args.box_tris,
               hand_tris=args.hand_tris, margin=args.margin)
    if rank == 0:
        total = args.num_envs * world_size
        print(f"[env] {args.num_envs} worlds x {world_size} rank(s) = {total} worlds, "
              f"{len(env.env.clip_names)} clips, act {env.num_actions}")
        print(f"[env] REFINER stage: actor reads the {OBS_DIMS['critic']}-D privileged "
              f"group (no teacher)")
        print(f"[env] box_tris={args.box_tris} hand_tris={args.hand_tris} "
              f"margin={args.margin} mu={args.mu} substeps={args.substeps}")
        print(f"[env] batch/iteration = {24 * total} samples")

    log_dir = Path(args.log_root) / args.run_name
    log_dir.mkdir(parents=True, exist_ok=True)
    if args.logger == "wandb":
        bind_wandb_run(log_dir, project=args.wandb_project, stage="refiner", rank=rank)
    runner = OnPolicyRunner(env, runner_cfg(args), log_dir=str(log_dir), device=args.device)
    if rank == 0:
        print(f"[alg] {type(runner.alg).__name__} (plain PPO, no distillation)"
              + (f"  (DDP, {world_size} ranks)" if world_size > 1 else ""))
    if args.resume:
        runner.load(args.resume)
        if rank == 0:
            print(f"[alg] resumed from {args.resume} at iteration "
                  f"{runner.current_learning_iteration}")

    if rank == 0 and (args.eval_minutes > 0 or args.video_interval > 0):
        attach_video(runner, args)

    todo = args.max_iterations - runner.current_learning_iteration
    if todo <= 0:
        if rank == 0:
            print(f"[alg] already at iteration {runner.current_learning_iteration} of "
                  f"{args.max_iterations}; nothing to do")
        return
    if rank == 0:
        print(f"[alg] training {todo} iterations to reach {args.max_iterations}")
    runner.learn(num_learning_iterations=todo, init_at_random_ep_len=True)


if __name__ == "__main__":
    main()
